// ============================================================
// core/title-data.js — Danh hiệu tự động unlock theo milestone
// Pure data — không import state hay engine
// ============================================================

// condition: hàm (G) => boolean
// Mỗi title có: id, name, nameCN, rarity, desc, condition, flavor
// rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary'

export const TITLES = [
  // ---- Realm milestones ----
  {
    id: 'first_step',
    name: 'Bước Đầu Tu Tiên',
    nameCN: '初入仙途',
    rarity: 'common',
    emoji: '🌱',
    desc: 'Đặt chân lên con đường tu tiên lần đầu.',
    flavor: 'Vạn dặm bắt đầu từ một bước.',
    condition: G => G.setupDone,
  },
  {
    id: 'truc_co',
    name: 'Trúc Cơ Thành Công',
    nameCN: '築基有成',
    rarity: 'uncommon',
    emoji: '🌀',
    desc: 'Đạt cảnh giới Trúc Cơ.',
    flavor: 'Nền móng vững chắc, tiên đạo rộng mở.',
    condition: G => G.realmIdx >= 1,
  },
  {
    id: 'kim_dan',
    name: 'Kim Đan Ngưng Tụ',
    nameCN: '金丹凝結',
    rarity: 'rare',
    emoji: '⚡',
    desc: 'Ngưng tụ Kim Đan thành công.',
    flavor: 'Kim đan chói sáng — ngươi đã vượt thoát phàm thai.',
    condition: G => G.realmIdx >= 2,
  },
  {
    id: 'nguyen_anh',
    name: 'Nguyên Anh Xuất Thế',
    nameCN: '元嬰出世',
    rarity: 'epic',
    emoji: '🔥',
    desc: 'Nguyên Anh phá Kim Đan, xuất thế bái thiên địa.',
    flavor: 'Tiếng khóc của Nguyên Anh rung chuyển cả vùng trời.',
    condition: G => G.realmIdx >= 3,
  },
  {
    id: 'hoa_than',
    name: 'Hóa Thần Nhập Đạo',
    nameCN: '化神入道',
    rarity: 'epic',
    emoji: '✨',
    desc: 'Thân thể bắt đầu hòa nhập với thiên đạo.',
    flavor: 'Khi thần hóa thành đạo, vạn vật đều là ta.',
    condition: G => G.realmIdx >= 4,
  },
  {
    id: 'luyen_hu',
    name: 'Luyện Hư Hợp Đạo',
    nameCN: '煉虛合道',
    rarity: 'legendary',
    emoji: '💫',
    desc: 'Hòa hợp với hư không vũ trụ.',
    flavor: 'Hư không là nhà, vũ trụ là thân.',
    condition: G => G.realmIdx >= 5,
  },
  {
    id: 'hop_the',
    name: 'Hợp Thể Siêu Việt',
    nameCN: '合體超越',
    rarity: 'legendary',
    emoji: '🌌',
    desc: 'Thân và thiên địa hòa làm một.',
    flavor: 'Một lời nói có thể di sơn đảo hải.',
    condition: G => G.realmIdx >= 6,
  },
  {
    id: 'dai_thua',
    name: 'Đại Thừa Đỉnh Phong',
    nameCN: '大乘巔峰',
    rarity: 'legendary',
    emoji: '☀',
    desc: 'Đứng ở đỉnh cao tu tiên, chỉ còn một bước là thành tiên.',
    flavor: 'Thiên hạ chỉ có ta là nhất.',
    condition: G => G.realmIdx >= 7,
  },

  // ---- Combat titles ----
  {
    id: 'first_blood',
    name: 'Sơ Sát',
    nameCN: '初殺',
    rarity: 'common',
    emoji: '🗡',
    desc: 'Giết yêu thú đầu tiên.',
    flavor: 'Lần đầu tiên tay nhuốm máu yêu.',
    condition: G => (G.totalKills || 0) >= 1,
  },
  {
    id: 'hunter',
    name: 'Liệp Yêu Giả',
    nameCN: '獵妖者',
    rarity: 'common',
    emoji: '🏹',
    desc: 'Tiêu diệt 10 yêu thú.',
    flavor: 'Bước chân ngươi khiến yêu tộc run rẩy.',
    condition: G => (G.totalKills || 0) >= 10,
  },
  {
    id: 'demon_slayer',
    name: 'Trảm Yêu Đại Sư',
    nameCN: '斬妖大師',
    rarity: 'uncommon',
    emoji: '⚔',
    desc: 'Tiêu diệt 50 yêu thú.',
    flavor: 'Tên tuổi ngươi được khắc vào bia trảm yêu.',
    condition: G => (G.totalKills || 0) >= 50,
  },
  {
    id: 'war_god',
    name: 'Chiến Thần',
    nameCN: '戰神',
    rarity: 'rare',
    emoji: '⚡',
    desc: 'Tiêu diệt 200 yêu thú.',
    flavor: 'Chiến thần giáng thế, vạn yêu thần phục.',
    condition: G => (G.totalKills || 0) >= 200,
  },
  {
    id: 'massacre',
    name: 'Sát Thần',
    nameCN: '殺神',
    rarity: 'epic',
    emoji: '💀',
    desc: 'Tiêu diệt 1000 yêu thú.',
    flavor: 'Sát khí xung thiên, cả thiên địa đổi màu.',
    condition: G => (G.totalKills || 0) >= 1000,
  },

  // ---- Alchemy titles ----
  {
    id: 'first_pill',
    name: 'Luyện Đan Sơ Học',
    nameCN: '煉丹初學',
    rarity: 'common',
    emoji: '⚗',
    desc: 'Luyện thành công viên đan đầu tiên.',
    flavor: 'Mùi thuốc đầu tiên thoảng trong không khí.',
    condition: G => (G.alchemySuccess || 0) >= 1,
  },
  {
    id: 'alchemist',
    name: 'Đan Sư',
    nameCN: '丹師',
    rarity: 'uncommon',
    emoji: '🔮',
    desc: 'Luyện thành công 20 viên đan.',
    flavor: 'Bàn tay ngươi đã quen với lửa thiêng.',
    condition: G => (G.alchemySuccess || 0) >= 20,
  },
  {
    id: 'grand_alchemist',
    name: 'Đại Đan Sư',
    nameCN: '大丹師',
    rarity: 'rare',
    emoji: '✨',
    desc: 'Luyện thành công 100 viên đan.',
    flavor: 'Đan hương bay xa ngàn dặm, ai ai cũng tìm đến.',
    condition: G => (G.alchemySuccess || 0) >= 100,
  },
  {
    id: 'pill_saint',
    name: 'Đan Thánh',
    nameCN: '丹聖',
    rarity: 'legendary',
    emoji: '🌟',
    desc: 'Luyện thành công 500 viên đan.',
    flavor: 'Đan Thánh giáng thế — một viên đan có thể đổi lấy tính mạng cường giả.',
    condition: G => (G.alchemySuccess || 0) >= 500,
  },

  // ---- Breakthrough titles ----
  {
    id: 'breaker',
    name: 'Đột Phá Giả',
    nameCN: '突破者',
    rarity: 'common',
    emoji: '💥',
    desc: 'Đột phá thành công 5 lần.',
    flavor: 'Mỗi đột phá là một lần tái sinh.',
    condition: G => (G.breakthroughs || 0) >= 5,
  },
  {
    id: 'iron_will',
    name: 'Ý Chí Thép',
    nameCN: '鐵志',
    rarity: 'uncommon',
    emoji: '🔱',
    desc: 'Đột phá thành công 20 lần.',
    flavor: 'Ý chí như thép, không gì có thể ngăn cản.',
    condition: G => (G.breakthroughs || 0) >= 20,
  },

  // ---- Quest titles ----
  {
    id: 'quester',
    name: 'Nhiệm Vụ Giả',
    nameCN: '任務者',
    rarity: 'common',
    emoji: '📜',
    desc: 'Hoàn thành 5 nhiệm vụ.',
    flavor: 'Con đường tu tiên không chỉ là luyện công.',
    condition: G => (G.totalQuestsCompleted || 0) >= 5,
  },
  {
    id: 'hero',
    name: 'Anh Hùng',
    nameCN: '英雄',
    rarity: 'rare',
    emoji: '🏆',
    desc: 'Hoàn thành 20 nhiệm vụ.',
    flavor: 'Tên tuổi ngươi được ghi vào sử sách của cõi tu tiên.',
    condition: G => (G.totalQuestsCompleted || 0) >= 20,
  },

  // ---- Prestige titles ----
  {
    id: 'reborn',
    name: 'Luân Hồi Giả',
    nameCN: '輪迴者',
    rarity: 'rare',
    emoji: '🔄',
    desc: 'Trải qua Luân Hồi lần đầu.',
    flavor: 'Chết đi sống lại, mỗi lần mạnh hơn một bậc.',
    condition: G => (G.prestige?.count || 0) >= 1,
  },
  {
    id: 'immortal_cycle',
    name: 'Bất Diệt Luân Hồi',
    nameCN: '不滅輪迴',
    rarity: 'legendary',
    emoji: '♾',
    desc: 'Trải qua 5 lần Luân Hồi.',
    flavor: 'Vòng luân hồi không có điểm dừng — chỉ có ngươi là trường tồn.',
    condition: G => (G.prestige?.count || 0) >= 5,
  },

  // ---- Special / hidden titles ----
  {
    id: 'meditator',
    name: 'Thiền Định Cao Nhân',
    nameCN: '禪定高人',
    rarity: 'uncommon',
    emoji: '🧘',
    desc: 'Bế quan trong thời gian dài.',
    flavor: 'Tĩnh như mặt hồ, động như sấm sét.',
    condition: G => (G.totalTime || 0) >= 3600, // 1 giờ
  },
  {
    id: 'rich',
    name: 'Phú Giả Nhân',
    nameCN: '富甲仙門',
    rarity: 'uncommon',
    emoji: '💎',
    desc: 'Tích lũy 10,000 linh thạch.',
    flavor: 'Tiền không phải tất cả, nhưng không có tiền thì không làm được gì.',
    condition: G => (G.stone || 0) >= 10000,
  },
  {
    id: 'millionaire',
    name: 'Linh Thạch Đại Gia',
    nameCN: '靈石大家',
    rarity: 'rare',
    emoji: '💰',
    desc: 'Tích lũy 1,000,000 linh thạch.',
    flavor: 'Của cải dồi dào, mua được cả tiên đan.',
    condition: G => (G.stone || 0) >= 1000000,
  },
];

export const RARITY_ORDER = ['common','uncommon','rare','epic','legendary'];
