// ============================================================
// combat/combat-data.js — Enemies, combat skills, combos
// v2 — 65 enemy phủ đều 8 realm, 15 player skills, ngũ hành
// ============================================================

// ---- Enemy definitions ----
// minRealm: player cần đạt realm này mới gặp
// element: ngũ hành của enemy (kim/moc/tu/thuy/huo/loi/bang/phong)
// element_weakness: hệ khắc chế enemy này
export const ENEMIES = [

  // ============================================================
  // REALM 0 — Luyện Khí (giai đoạn 1-3)
  // ============================================================
  {
    id: 'linh_tho',
    name: 'Linh Thổ Thỏ', emoji: '🐇',
    minRealm: 0, tier: 1, element: 'tu',
    hpBase: 25, atkBase: 2, defBase: 2, spdBase: 18,
    hpScale: 1.2, atkScale: 1.1,
    expReward: 6, stoneReward: [2, 6],
    skills: ['dodge'],
    drops: [
      { itemId: 'rabbit_fur',  chance: 0.80, qty: [1, 2] },
      { itemId: 'spirit_herb', chance: 0.30, qty: [1, 1] },
    ],
    element_weakness: 'kim',
    lore: 'Thỏ ăn linh thảo, lông trắng tinh. Không nguy hiểm nhưng chạy rất nhanh.',
    deathText: 'Linh Thổ Thỏ ngã xuống, lông trắng vương vấn!',
  },
  {
    id: 'hoa_thu',
    name: 'Hỏa Thử', emoji: '🐀',
    minRealm: 0, tier: 1, element: 'huo',
    hpBase: 30, atkBase: 3, defBase: 1, spdBase: 15,
    hpScale: 1.3, atkScale: 1.2,
    expReward: 8, stoneReward: [3, 8],
    skills: ['bite'],
    drops: [
      { itemId: 'rat_fur',      chance: 0.70, qty: [1, 2] },
      { itemId: 'fire_essence', chance: 0.10, qty: [1, 1] },
    ],
    element_weakness: 'thuy',
    lore: 'Chuột hỏa hệ, lông cháy đỏ. Dễ tiêu diệt nhưng đi thành bầy.',
    deathText: 'Hỏa Thử bốc lửa một chút rồi tắt lịm!',
  },
  {
    id: 'linh_tuoc',
    name: 'Linh Tước', emoji: '🐦',
    minRealm: 0, tier: 1, element: 'phong',
    hpBase: 20, atkBase: 4, defBase: 1, spdBase: 20,
    hpScale: 1.2, atkScale: 1.2,
    expReward: 7, stoneReward: [3, 7],
    skills: ['peck', 'fly_dodge'],
    drops: [
      { itemId: 'bird_feather', chance: 0.75, qty: [1, 3] },
    ],
    element_weakness: 'loi',
    lore: 'Chim nhỏ có linh khí phong hệ. Lông vũ dùng luyện đan.',
    deathText: 'Linh Tước rơi xuống, lông vũ tung bay!',
  },
  {
    id: 'doc_diep',
    name: 'Độc Điệp', emoji: '🦋',
    minRealm: 0, tier: 1, element: 'moc',
    hpBase: 18, atkBase: 3, defBase: 0, spdBase: 22,
    hpScale: 1.2, atkScale: 1.15,
    expReward: 9, stoneReward: [2, 5],
    skills: ['poison_dust'],
    drops: [
      { itemId: 'butterfly_wing', chance: 0.60, qty: [1, 2] },
      { itemId: 'poison_sac',     chance: 0.40, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Bướm đẹp nhưng vảy cánh có độc. Cẩn thận khi gần.',
    deathText: 'Độc Điệp tan thành bột phát sáng!',
  },
  {
    id: 'demon_wolf',
    name: 'Yêu Sói Đen', emoji: '🐺',
    minRealm: 0, tier: 2, element: 'huo',
    hpBase: 120, atkBase: 8, defBase: 2, spdBase: 12,
    hpScale: 1.4, atkScale: 1.3,
    expReward: 30, stoneReward: [15, 30],
    skills: ['claw_strike', 'howl'],
    drops: [
      { itemId: 'wolf_fang',    chance: 0.60, qty: [1, 2] },
      { itemId: 'demon_core_1', chance: 0.15, qty: [1, 1] },
    ],
    element_weakness: 'thuy',
    lore: 'Yêu thú bậc thấp, di chuyển nhanh nhẹn nhưng phòng thủ mỏng.',
    deathText: 'Yêu Sói Đen rú lên rồi tan thành khí xám!',
  },
  {
    id: 'stone_golem',
    name: 'Thổ Nguyên Quỷ', emoji: '🗿',
    minRealm: 0, tier: 2, element: 'tu',
    hpBase: 250, atkBase: 12, defBase: 15, spdBase: 5,
    hpScale: 1.5, atkScale: 1.2,
    expReward: 45, stoneReward: [20, 45],
    skills: ['heavy_blow', 'stone_skin'],
    drops: [
      { itemId: 'earth_stone',  chance: 0.70, qty: [1, 3] },
      { itemId: 'stone_scale',  chance: 0.40, qty: [1, 2] },
      { itemId: 'demon_core_1', chance: 0.10, qty: [1, 1] },
    ],
    element_weakness: 'moc',
    lore: 'Thổ linh kết thành hình người. Chậm nhưng mỗi đòn như núi đổ.',
    deathText: 'Thổ Nguyên Quỷ vỡ vụn thành đá!',
  },
  {
    id: 'fire_fox',
    name: 'Hỏa Linh Hồ', emoji: '🦊',
    minRealm: 0, tier: 2, element: 'huo',
    hpBase: 180, atkBase: 18, defBase: 5, spdBase: 18,
    hpScale: 1.4, atkScale: 1.35,
    expReward: 60, stoneReward: [25, 50],
    skills: ['fire_breath', 'agility'],
    drops: [
      { itemId: 'fox_tail',     chance: 0.50, qty: [1, 1] },
      { itemId: 'fire_essence', chance: 0.40, qty: [1, 2] },
      { itemId: 'demon_core_1', chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'thuy',
    lore: 'Tu luyện từ hồ bình thường, đã ngưng tụ hỏa linh. Ma mị và nguy hiểm.',
    deathText: 'Hỏa Linh Hồ kêu một tiếng rồi lửa tắt!',
  },

  // ============================================================
  // REALM 0 — Luyện Khí (giai đoạn 4-6)
  // ============================================================
  {
    id: 'hoa_nga_tru',
    name: 'Hỏa Nha Trư', emoji: '🐗',
    minRealm: 0, tier: 2, element: 'huo',
    hpBase: 90, atkBase: 10, defBase: 6, spdBase: 10,
    hpScale: 1.35, atkScale: 1.25,
    expReward: 22, stoneReward: [10, 22],
    skills: ['charge', 'fire_tusk'],
    drops: [
      { itemId: 'boar_tusk',    chance: 0.65, qty: [1, 2] },
      { itemId: 'fire_essence', chance: 0.30, qty: [1, 1] },
      { itemId: 'demon_core_1', chance: 0.08, qty: [1, 1] },
    ],
    element_weakness: 'thuy',
    lore: 'Lợn rừng to lớn, nanh bốc lửa. Tấn công húc cực kỳ nguy hiểm.',
    deathText: 'Hỏa Nha Trư ngã đổ, lửa tắt dần trên nanh!',
  },
  {
    id: 'thach_bi_than_lan',
    name: 'Thạch Bì Thằn Lằn', emoji: '🦎',
    minRealm: 0, tier: 2, element: 'tu',
    hpBase: 120, atkBase: 8, defBase: 18, spdBase: 7,
    hpScale: 1.4, atkScale: 1.2,
    expReward: 25, stoneReward: [12, 25],
    skills: ['stone_skin', 'tail_whip'],
    drops: [
      { itemId: 'stone_scale',  chance: 0.70, qty: [1, 3] },
      { itemId: 'earth_stone',  chance: 0.40, qty: [1, 2] },
      { itemId: 'demon_core_1', chance: 0.10, qty: [1, 1] },
    ],
    element_weakness: 'moc',
    lore: 'Da đá, gần như không thể xuyên qua bằng vũ khí thường.',
    deathText: 'Thạch Bì Thằn Lằn vỡ vụn như đá!',
  },
  {
    id: 'son_ung_linh',
    name: 'Sơn Ưng Linh', emoji: '🦅',
    minRealm: 0, tier: 2, element: 'phong',
    hpBase: 70, atkBase: 14, defBase: 4, spdBase: 20,
    hpScale: 1.3, atkScale: 1.3,
    expReward: 28, stoneReward: [12, 28],
    skills: ['dive_strike', 'wing_gust'],
    drops: [
      { itemId: 'eagle_claw',   chance: 0.55, qty: [1, 2] },
      { itemId: 'hawk_feather', chance: 0.50, qty: [1, 3] },
      { itemId: 'demon_core_1', chance: 0.12, qty: [1, 1] },
    ],
    element_weakness: 'loi',
    lore: 'Đại bàng linh sơn, mắt nhìn xa trăm dặm. Tấn công từ trên trời xuống.',
    deathText: 'Sơn Ưng Linh ngã xuống từ bầu trời, cánh tan vỡ!',
  },
  {
    id: 'thuy_linh_ech',
    name: 'Thủy Linh Ếch', emoji: '🐸',
    minRealm: 0, tier: 2, element: 'thuy',
    hpBase: 80, atkBase: 9, defBase: 8, spdBase: 14,
    hpScale: 1.3, atkScale: 1.2,
    expReward: 20, stoneReward: [8, 20],
    skills: ['water_spit', 'slippery'],
    drops: [
      { itemId: 'frog_skin',    chance: 0.65, qty: [1, 2] },
      { itemId: 'moon_dew',     chance: 0.25, qty: [1, 1] },
    ],
    element_weakness: 'tu',
    lore: 'Ếch hấp thụ linh khí từ hồ, da tiết ra chất lỏng linh..',
    deathText: 'Thủy Linh Ếch tan vào nước!',
  },
  {
    id: 'moc_nhan',
    name: 'Mộc Nhân Yêu', emoji: '🌳',
    minRealm: 0, tier: 2, element: 'moc',
    hpBase: 150, atkBase: 11, defBase: 10, spdBase: 6,
    hpScale: 1.35, atkScale: 1.25,
    expReward: 32, stoneReward: [14, 32],
    skills: ['vine_whip', 'root_bind'],
    drops: [
      { itemId: 'spirit_herb',  chance: 0.70, qty: [1, 3] },
      { itemId: 'jade_lotus',   chance: 0.20, qty: [1, 1] },
      { itemId: 'demon_core_1', chance: 0.12, qty: [1, 1] },
    ],
    element_weakness: 'kim',
    lore: 'Cây cổ thụ hấp thụ linh khí ngàn năm, hình thành ý thức và bắt đầu tấn công sinh vật.',
    deathText: 'Mộc Nhân Yêu gãy đổ, tan thành mùn gỗ!',
  },

  // ============================================================
  // REALM 0 — Luyện Khí (giai đoạn 7-9, boss nhỏ)
  // ============================================================
  {
    id: 'kim_gia_quy',
    name: 'Kim Giáp Quỷ', emoji: '🦀',
    minRealm: 0, tier: 3, element: 'kim',
    hpBase: 350, atkBase: 22, defBase: 30, spdBase: 8,
    hpScale: 1.5, atkScale: 1.3,
    expReward: 80, stoneReward: [35, 70],
    skills: ['claw_strike', 'stone_skin', 'iron_shell'],
    drops: [
      { itemId: 'gold_shell',   chance: 0.55, qty: [1, 2] },
      { itemId: 'earth_stone',  chance: 0.50, qty: [1, 3] },
      { itemId: 'demon_core_1', chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Con quỷ giáp kim loại, đầy mình là lớp giáp cứng như thiết thạch.',
    deathText: 'Kim Giáp Quỷ vỡ vụn, giáp kim loại rơi tứ tán!',
  },
  {
    id: 'loi_linh_than',
    name: 'Lôi Linh Sâu', emoji: '🐛',
    minRealm: 0, tier: 3, element: 'loi',
    hpBase: 200, atkBase: 28, defBase: 8, spdBase: 10,
    hpScale: 1.4, atkScale: 1.35,
    expReward: 70, stoneReward: [30, 60],
    skills: ['lightning_strike', 'coil'],
    drops: [
      { itemId: 'lightning_core', chance: 0.20, qty: [1, 1] },
      { itemId: 'hawk_feather',   chance: 0.40, qty: [1, 2] },
      { itemId: 'demon_core_1',   chance: 0.15, qty: [1, 1] },
    ],
    element_weakness: 'tu',
    lore: 'Sâu khổng lồ hấp thụ lôi khí từ đỉnh núi cao, toàn thân phóng điện.',
    deathText: 'Lôi Linh Sâu co giật rồi tắt điện!',
  },

  // ============================================================
  // REALM 1 — Trúc Cơ
  // ============================================================
  {
    id: 'thunder_hawk',
    name: 'Lôi Ưng Quỷ', emoji: '🦅',
    minRealm: 1, tier: 3, element: 'loi',
    hpBase: 500, atkBase: 40, defBase: 15, spdBase: 22,
    hpScale: 1.5, atkScale: 1.4,
    expReward: 120, stoneReward: [60, 120],
    skills: ['lightning_strike', 'dive_bomb', 'thunder_cry'],
    drops: [
      { itemId: 'hawk_feather',   chance: 0.60, qty: [1, 3] },
      { itemId: 'lightning_core', chance: 0.25, qty: [1, 1] },
      { itemId: 'demon_core_2',   chance: 0.15, qty: [1, 1] },
    ],
    element_weakness: 'tu',
    lore: 'Lôi Ưng Quỷ cưỡi sấm chớp, tiếng kêu xé màng nhĩ người tu luyện.',
    deathText: 'Lôi Ưng Quỷ nổ tung giữa không trung, sấm chớp tản mát!',
  },
  {
    id: 'ice_serpent',
    name: 'Băng Hàn Xà', emoji: '🐍',
    minRealm: 1, tier: 3, element: 'bang',
    hpBase: 700, atkBase: 35, defBase: 25, spdBase: 15,
    hpScale: 1.6, atkScale: 1.3,
    expReward: 180, stoneReward: [80, 160],
    skills: ['ice_fang', 'freeze', 'coil'],
    drops: [
      { itemId: 'serpent_scale',  chance: 0.65, qty: [2, 4] },
      { itemId: 'ice_crystal',    chance: 0.40, qty: [1, 2] },
      { itemId: 'demon_core_2',   chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Xà yêu tu hàng trăm năm trong băng sơn, độc lạnh có thể đóng băng kinh mạch.',
    deathText: 'Băng Hàn Xà vỡ ra thành ngàn mảnh băng!',
  },
  {
    id: 'thuy_long_gui',
    name: 'Thủy Long Quy', emoji: '🐢',
    minRealm: 1, tier: 3, element: 'thuy',
    hpBase: 900, atkBase: 28, defBase: 50, spdBase: 6,
    hpScale: 1.55, atkScale: 1.25,
    expReward: 150, stoneReward: [70, 140],
    skills: ['water_cannon', 'shell_guard', 'heavy_blow'],
    drops: [
      { itemId: 'turtle_shell',  chance: 0.55, qty: [1, 2] },
      { itemId: 'serpent_scale', chance: 0.35, qty: [1, 2] },
      { itemId: 'demon_core_2',  chance: 0.18, qty: [1, 1] },
    ],
    element_weakness: 'tu',
    lore: 'Rùa khổng lồ có tuổi thọ ngàn năm, mai cứng như thành lũy.',
    deathText: 'Thủy Long Quy thu mình vào mai rồi chìm xuống đất!',
  },
  {
    id: 'phong_linh_mieu',
    name: 'Phong Linh Miêu', emoji: '🐱',
    minRealm: 1, tier: 3, element: 'phong',
    hpBase: 450, atkBase: 45, defBase: 12, spdBase: 30,
    hpScale: 1.45, atkScale: 1.4,
    expReward: 140, stoneReward: [65, 130],
    skills: ['wind_claw', 'agility', 'phantom_strike'],
    drops: [
      { itemId: 'wind_fur',      chance: 0.50, qty: [1, 2] },
      { itemId: 'eagle_claw',    chance: 0.30, qty: [1, 1] },
      { itemId: 'demon_core_2',  chance: 0.15, qty: [1, 1] },
    ],
    element_weakness: 'loi',
    lore: 'Mèo yêu phong hệ, di chuyển nhanh như gió, móng vuốt sắc bén.',
    deathText: 'Phong Linh Miêu tan vào trong gió!',
  },
  {
    id: 'hoa_linh_niu',
    name: 'Hỏa Linh Ngưu', emoji: '🐂',
    minRealm: 1, tier: 3, element: 'huo',
    hpBase: 1200, atkBase: 55, defBase: 35, spdBase: 10,
    hpScale: 1.6, atkScale: 1.35,
    expReward: 200, stoneReward: [90, 180],
    skills: ['fire_charge', 'fire_breath', 'berserk'],
    drops: [
      { itemId: 'fire_core',     chance: 0.45, qty: [1, 1] },
      { itemId: 'fire_essence',  chance: 0.60, qty: [1, 3] },
      { itemId: 'demon_core_2',  chance: 0.22, qty: [1, 1] },
    ],
    element_weakness: 'thuy',
    lore: 'Trâu khổng lồ thân bốc lửa, húc một cái có thể hạ cả cây to.',
    deathText: 'Hỏa Linh Ngưu ngã xuống, lửa tắt dần!',
  },
  {
    id: 'kim_chi_hou',
    name: 'Kim Chỉ Hầu', emoji: '🐒',
    minRealm: 1, tier: 4, element: 'kim',
    hpBase: 600, atkBase: 50, defBase: 20, spdBase: 28,
    hpScale: 1.5, atkScale: 1.4,
    expReward: 160, stoneReward: [75, 150],
    skills: ['claw_strike', 'agility', 'iron_fist'],
    drops: [
      { itemId: 'monkey_staff',  chance: 0.40, qty: [1, 1] },
      { itemId: 'gold_shell',    chance: 0.35, qty: [1, 2] },
      { itemId: 'demon_core_2',  chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Khỉ vàng linh hoạt, móng tay cứng như thép, đã tu luyện mấy trăm năm.',
    deathText: 'Kim Chỉ Hầu rú lên rồi ngã xuống cành cây!',
  },

  // ============================================================
  // REALM 2 — Kim Đan
  // ============================================================
  {
    id: 'demon_general',
    name: 'Yêu Tướng Hắc Giáp', emoji: '👹',
    minRealm: 2, tier: 4, element: 'am',
    hpBase: 3000, atkBase: 150, defBase: 80, spdBase: 18,
    hpScale: 1.7, atkScale: 1.5,
    expReward: 500, stoneReward: [200, 400],
    skills: ['dark_blade', 'demon_roar', 'armor_break', 'berserk'],
    drops: [
      { itemId: 'demon_armor',  chance: 0.30, qty: [1, 1] },
      { itemId: 'dark_essence', chance: 0.50, qty: [1, 3] },
      { itemId: 'demon_core_3', chance: 0.25, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Yêu tộc đại tướng, từng thống lĩnh vạn yêu, bị đánh bại rồi đọa vào chốn này.',
    deathText: 'Yêu Tướng Hắc Giáp gầm thét một tiếng, hào quang đen tắt lịm!',
  },
  {
    id: 'crimson_spider',
    name: 'Xích Hỏa Nhện', emoji: '🕷',
    minRealm: 2, tier: 4, element: 'huo',
    hpBase: 2200, atkBase: 120, defBase: 60, spdBase: 25,
    hpScale: 1.65, atkScale: 1.45,
    expReward: 420, stoneReward: [170, 340],
    skills: ['venom_bite', 'fire_web', 'coil'],
    drops: [
      { itemId: 'spider_silk',   chance: 0.60, qty: [1, 3] },
      { itemId: 'crimson_herb',  chance: 0.30, qty: [1, 1] },
      { itemId: 'demon_core_3',  chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'bang',
    lore: 'Nhện khổng lồ có tơ bốc lửa, dệt bẫy bằng tơ bắt lửa để săn mồi.',
    deathText: 'Xích Hỏa Nhện cháy thành tro trong chính lưới lửa của nó!',
  },
  {
    id: 'thach_khong_vi',
    name: 'Thạch Không Vị', emoji: '🦏',
    minRealm: 2, tier: 4, element: 'tu',
    hpBase: 4500, atkBase: 200, defBase: 150, spdBase: 8,
    hpScale: 1.75, atkScale: 1.4,
    expReward: 600, stoneReward: [250, 500],
    skills: ['stone_armor', 'earth_quake', 'heavy_blow'],
    drops: [
      { itemId: 'rhino_horn',    chance: 0.40, qty: [1, 1] },
      { itemId: 'earth_stone',   chance: 0.70, qty: [2, 5] },
      { itemId: 'demon_core_3',  chance: 0.22, qty: [1, 1] },
    ],
    element_weakness: 'moc',
    lore: 'Tê giác đá khổng lồ, sừng có thể xuyên thành. Chậm nhưng không thể ngăn cản.',
    deathText: 'Thạch Không Vị ngã xuống, mặt đất rung chuyển!',
  },
  {
    id: 'xanh_long_xa',
    name: 'Thanh Long Xà', emoji: '🐲',
    minRealm: 2, tier: 4, element: 'moc',
    hpBase: 2800, atkBase: 140, defBase: 90, spdBase: 20,
    hpScale: 1.7, atkScale: 1.45,
    expReward: 480, stoneReward: [190, 380],
    skills: ['vine_whip', 'venom_bite', 'coil', 'jade_scales'],
    drops: [
      { itemId: 'green_scale',   chance: 0.55, qty: [1, 2] },
      { itemId: 'blood_ginseng', chance: 0.25, qty: [1, 1] },
      { itemId: 'demon_core_3',  chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'kim',
    lore: 'Xà rồng xanh lục, toàn thân quấn dây leo linh. Nọc độc có thể khô kiệt linh lực.',
    deathText: 'Thanh Long Xà tan vào rừng sâu!',
  },
  {
    id: 'bang_linh_gau',
    name: 'Băng Linh Hùng', emoji: '🐻',
    minRealm: 2, tier: 5, element: 'bang',
    hpBase: 5000, atkBase: 180, defBase: 120, spdBase: 12,
    hpScale: 1.75, atkScale: 1.5,
    expReward: 650, stoneReward: [270, 540],
    skills: ['blizzard', 'heavy_blow', 'ice_prison'],
    drops: [
      { itemId: 'ice_crystal',   chance: 0.65, qty: [2, 4] },
      { itemId: 'frost_fur',     chance: 0.45, qty: [1, 2] },
      { itemId: 'demon_core_3',  chance: 0.25, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Gấu băng khổng lồ, hơi thở tạo ra bão tuyết nhỏ. Ẩn náu trong hang đá sâu.',
    deathText: 'Băng Linh Hùng tan chảy chậm chạp!',
  },

  // ============================================================
  // REALM 3 — Nguyên Anh
  // ============================================================
  {
    id: 'blood_bat',
    name: 'Huyết Dực Ma Thú', emoji: '🦇',
    minRealm: 3, tier: 5, element: 'am',
    hpBase: 8000, atkBase: 400, defBase: 180, spdBase: 28,
    hpScale: 1.7, atkScale: 1.55,
    expReward: 800, stoneReward: [350, 700],
    skills: ['blood_drain', 'wing_slash', 'fear'],
    drops: [
      { itemId: 'blood_crystal', chance: 0.55, qty: [1, 2] },
      { itemId: 'demon_core_3',  chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Ma thú uống máu tu luyện qua ngàn năm, thân hình to bằng gian phòng.',
    deathText: 'Huyết Dực Ma Thú vỡ tan thành mưa máu!',
  },
  {
    id: 'jade_serpent',
    name: 'Bích Ngọc Thần Xà', emoji: '🐍',
    minRealm: 3, tier: 5, element: 'moc',
    hpBase: 10000, atkBase: 350, defBase: 250, spdBase: 22,
    hpScale: 1.75, atkScale: 1.5,
    expReward: 1000, stoneReward: [400, 800],
    skills: ['venom_bite', 'coil', 'jade_scales'],
    drops: [
      { itemId: 'jade_serpent_gall', chance: 0.40, qty: [1, 1] },
      { itemId: 'blood_crystal',     chance: 0.35, qty: [1, 3] },
      { itemId: 'demon_core_3',      chance: 0.25, qty: [1, 1] },
    ],
    element_weakness: 'kim',
    lore: 'Thần xà bích ngọc, vảy cứng như thép tiên, nọc độc ăn mòn linh lực.',
    deathText: 'Bích Ngọc Thần Xà trút hơi thở cuối, thân hóa thành linh ngọc!',
  },
  {
    id: 'phantom_fox',
    name: 'Ảo Ảnh Cửu Vĩ Hồ', emoji: '🦊',
    minRealm: 3, tier: 6, element: 'am',
    hpBase: 12000, atkBase: 500, defBase: 200, spdBase: 35,
    hpScale: 1.8, atkScale: 1.6,
    expReward: 1200, stoneReward: [500, 1000],
    skills: ['phantom_strike', 'illusion', 'nine_tails'],
    drops: [
      { itemId: 'phantom_fur',  chance: 0.45, qty: [1, 2] },
      { itemId: 'void_grass',   chance: 0.30, qty: [1, 2] },
      { itemId: 'demon_core_3', chance: 0.30, qty: [1, 1] },
    ],
    element_weakness: 'loi',
    lore: 'Cửu Vĩ Hồ đã tu luyện ngàn năm, có thể hóa hình người và tạo ảo cảnh.',
    deathText: 'Ảo ảnh tan biến, Cửu Vĩ Hồ thét lên rồi hóa thành ánh sáng!',
  },
  {
    id: 'loi_linh_long',
    name: 'Lôi Linh Long Xà', emoji: '🐊',
    minRealm: 3, tier: 5, element: 'loi',
    hpBase: 9000, atkBase: 450, defBase: 200, spdBase: 20,
    hpScale: 1.72, atkScale: 1.52,
    expReward: 900, stoneReward: [380, 760],
    skills: ['lightning_strike', 'dragon_tail', 'thunder_cry'],
    drops: [
      { itemId: 'lightning_core', chance: 0.40, qty: [1, 2] },
      { itemId: 'blood_crystal',  chance: 0.30, qty: [1, 2] },
      { itemId: 'demon_core_3',   chance: 0.22, qty: [1, 1] },
    ],
    element_weakness: 'tu',
    lore: 'Rồng nhỏ hấp thụ lôi khí, toàn thân phóng điện liên tục.',
    deathText: 'Lôi Linh Long Xà nổ tung thành tia điện!',
  },
  {
    id: 'hoa_phuong_hoang',
    name: 'Hỏa Phượng Hoàng Con', emoji: '🦜',
    minRealm: 3, tier: 5, element: 'huo',
    hpBase: 7500, atkBase: 480, defBase: 160, spdBase: 32,
    hpScale: 1.68, atkScale: 1.58,
    expReward: 850, stoneReward: [360, 720],
    skills: ['fire_breath', 'wing_slash', 'agility', 'berserk'],
    drops: [
      { itemId: 'phoenix_feather', chance: 0.40, qty: [1, 1] },
      { itemId: 'fire_essence',    chance: 0.60, qty: [2, 4] },
      { itemId: 'demon_core_3',    chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'bang',
    lore: 'Phượng hoàng chưa trưởng thành, nhưng ngọn lửa đã đủ thiêu rụi khu rừng.',
    deathText: 'Hỏa Phượng Hoàng bùng lên lần cuối rồi tắt!',
  },

  // ============================================================
  // REALM 4 — Hóa Thần
  // ============================================================
  {
    id: 'earth_dragon',
    name: 'Địa Long Cổ Thần', emoji: '🐊',
    minRealm: 4, tier: 6, element: 'tu',
    hpBase: 25000, atkBase: 900, defBase: 500, spdBase: 15,
    hpScale: 1.8, atkScale: 1.6,
    expReward: 2000, stoneReward: [900, 1800],
    skills: ['earth_quake', 'dragon_tail', 'stone_armor', 'berserk'],
    drops: [
      { itemId: 'earth_dragon_core', chance: 0.35, qty: [1, 1] },
      { itemId: 'demon_core_3',      chance: 0.40, qty: [1, 2] },
      { itemId: 'heaven_stone',      chance: 0.15, qty: [1, 1] },
    ],
    element_weakness: 'moc',
    lore: 'Cổ thần thời thượng cổ, một cú quẫy đuôi có thể san bằng núi.',
    deathText: 'Địa Long gầm thét, mặt đất rung chuyển khi nó ngã xuống!',
  },
  {
    id: 'wind_roc',
    name: 'Đại Bằng Phong Thần', emoji: '🦅',
    minRealm: 4, tier: 6, element: 'phong',
    hpBase: 20000, atkBase: 1100, defBase: 350, spdBase: 45,
    hpScale: 1.75, atkScale: 1.65,
    expReward: 2200, stoneReward: [1000, 2000],
    skills: ['gale_strike', 'wind_vortex', 'sonic_boom'],
    drops: [
      { itemId: 'roc_feather',  chance: 0.50, qty: [1, 2] },
      { itemId: 'phantom_fur',  chance: 0.25, qty: [1, 1] },
      { itemId: 'demon_core_3', chance: 0.35, qty: [1, 2] },
    ],
    element_weakness: 'loi',
    lore: 'Thần điểu của bầu trời, sải cánh che kín mặt trời.',
    deathText: 'Đại Bằng kêu một tiếng ai oán, lông vũ bay tứ tán trong gió!',
  },
  {
    id: 'kim_long_than',
    name: 'Kim Long Thần', emoji: '🐉',
    minRealm: 4, tier: 6, element: 'kim',
    hpBase: 30000, atkBase: 1200, defBase: 600, spdBase: 22,
    hpScale: 1.82, atkScale: 1.62,
    expReward: 2500, stoneReward: [1200, 2400],
    skills: ['dark_blade', 'armor_break', 'dragon_tail', 'berserk'],
    drops: [
      { itemId: 'dragon_scale', chance: 0.30, qty: [1, 1] },
      { itemId: 'gold_shell',   chance: 0.55, qty: [1, 3] },
      { itemId: 'heaven_stone', chance: 0.18, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Rồng kim loại thượng cổ, vảy cứng như kim cương thiên.',
    deathText: 'Kim Long Thần ngã xuống, vảy vàng tung tóe!',
  },
  {
    id: 'hoa_than_phung',
    name: 'Hỏa Thần Phụng', emoji: '🦚',
    minRealm: 4, tier: 6, element: 'huo',
    hpBase: 22000, atkBase: 1300, defBase: 400, spdBase: 38,
    hpScale: 1.78, atkScale: 1.68,
    expReward: 2300, stoneReward: [1100, 2200],
    skills: ['fire_breath', 'nine_tails', 'agility', 'berserk'],
    drops: [
      { itemId: 'phoenix_feather', chance: 0.45, qty: [1, 2] },
      { itemId: 'crimson_herb',    chance: 0.60, qty: [2, 4] },
      { itemId: 'heaven_stone',    chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'thuy',
    lore: 'Thần điểu hỏa hệ, lông rực lửa thiêng, niên tuổi ngàn năm.',
    deathText: 'Hỏa Thần Phụng bùng cháy dữ dội rồi tắt lịm!',
  },

  // ============================================================
  // REALM 5 — Luyện Hư
  // ============================================================
  {
    id: 'void_demon',
    name: 'Hư Không Ma Vương', emoji: '👿',
    minRealm: 5, tier: 7, element: 'am',
    hpBase: 60000, atkBase: 2500, defBase: 1000, spdBase: 30,
    hpScale: 1.85, atkScale: 1.7,
    expReward: 5000, stoneReward: [2500, 5000],
    skills: ['void_slash', 'dimension_rip', 'demon_roar', 'berserk'],
    drops: [
      { itemId: 'void_core',    chance: 0.40, qty: [1, 1] },
      { itemId: 'dark_essence', chance: 0.60, qty: [2, 4] },
      { itemId: 'heaven_stone', chance: 0.25, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Ma vương từ hư không, thân thể là bóng tối ngưng tụ.',
    deathText: 'Hư Không Ma Vương rít lên, tan vào hư không!',
  },
  {
    id: 'frost_giant',
    name: 'Băng Nguyên Cổ Thần', emoji: '🧊',
    minRealm: 5, tier: 7, element: 'bang',
    hpBase: 80000, atkBase: 2000, defBase: 1500, spdBase: 12,
    hpScale: 1.9, atkScale: 1.65,
    expReward: 5500, stoneReward: [2800, 5500],
    skills: ['blizzard', 'ice_prison', 'glacier_stomp', 'armor_break'],
    drops: [
      { itemId: 'frost_heart', chance: 0.35, qty: [1, 1] },
      { itemId: 'ice_crystal', chance: 0.70, qty: [2, 5] },
      { itemId: 'void_core',   chance: 0.20, qty: [1, 1] },
    ],
    element_weakness: 'huo',
    lore: 'Cổ thần băng hà ngủ say ngàn năm trong lõi băng.',
    deathText: 'Băng Nguyên Cổ Thần tan chảy, để lại vũng nước đá lạnh buốt!',
  },
  {
    id: 'thien_loc_ky_lan',
    name: 'Thiên Lộc Kỳ Lân', emoji: '🦌',
    minRealm: 5, tier: 7, element: 'moc',
    hpBase: 70000, atkBase: 2200, defBase: 1200, spdBase: 40,
    hpScale: 1.87, atkScale: 1.68,
    expReward: 5200, stoneReward: [2600, 5200],
    skills: ['vine_whip', 'gale_strike', 'agility', 'horn_thrust'],
    drops: [
      { itemId: 'qilin_horn',  chance: 0.30, qty: [1, 1] },
      { itemId: 'void_core',   chance: 0.25, qty: [1, 1] },
      { itemId: 'immortal_root',chance: 0.15, qty: [1, 1] },
    ],
    element_weakness: 'kim',
    lore: 'Kỳ lân thiêng liêng mang linh khí mộc thuần khiết, sừng có thể chữa bách bệnh.',
    deathText: 'Thiên Lộc Kỳ Lân ngã xuống, đất nơi nó nằm nở ra hoa linh!',
  },

  // ============================================================
  // REALM 6 — Hợp Thể
  // ============================================================
  {
    id: 'celestial_tiger',
    name: 'Thiên Hổ Thần Vương', emoji: '🐅',
    minRealm: 6, tier: 8, element: 'loi',
    hpBase: 200000, atkBase: 7000, defBase: 3000, spdBase: 40,
    hpScale: 1.9, atkScale: 1.75,
    expReward: 12000, stoneReward: [6000, 12000],
    skills: ['tiger_roar', 'heaven_claw', 'divine_fang', 'berserk'],
    drops: [
      { itemId: 'tiger_soul',  chance: 0.40, qty: [1, 1] },
      { itemId: 'void_core',   chance: 0.35, qty: [1, 2] },
      { itemId: 'heaven_stone',chance: 0.30, qty: [1, 2] },
    ],
    element_weakness: 'tu',
    lore: 'Hổ vương tại thiên giới, thân mang thiên lôi, mắt bừng ánh sáng tử thần.',
    deathText: 'Thiên Hổ Thần Vương ngã xuống, tiếng rống vang vọng khắp thiên địa!',
  },
  {
    id: 'chaos_wyrm',
    name: 'Hỗn Độn Thần Long', emoji: '🐲',
    minRealm: 6, tier: 8, element: 'hun_don',
    hpBase: 300000, atkBase: 8000, defBase: 4000, spdBase: 25,
    hpScale: 2.0, atkScale: 1.8,
    expReward: 15000, stoneReward: [8000, 15000],
    skills: ['chaos_breath', 'divine_thunder', 'dragon_tail', 'armor_break'],
    drops: [
      { itemId: 'chaos_scale', chance: 0.45, qty: [1, 1] },
      { itemId: 'dragon_scale',chance: 0.50, qty: [1, 2] },
      { itemId: 'void_core',   chance: 0.40, qty: [1, 2] },
    ],
    element_weakness: null,
    lore: 'Long tộc thủy tổ từ thời khai thiên tịch địa, mang hỗn độn khí nguyên thủy.',
    deathText: 'Hỗn Độn Thần Long trút hơi thở cuối, hỗn độn khí tan vào trời đất!',
  },
  {
    id: 'xuan_ming_gui',
    name: 'Huyền Minh Thần Quy', emoji: '🐢',
    minRealm: 6, tier: 8, element: 'thuy',
    hpBase: 400000, atkBase: 5000, defBase: 8000, spdBase: 8,
    hpScale: 1.95, atkScale: 1.7,
    expReward: 14000, stoneReward: [7000, 14000],
    skills: ['water_cannon', 'shell_guard', 'blizzard', 'armor_break'],
    drops: [
      { itemId: 'chaos_scale',  chance: 0.35, qty: [1, 1] },
      { itemId: 'frost_heart',  chance: 0.40, qty: [1, 2] },
      { itemId: 'heaven_stone', chance: 0.40, qty: [2, 3] },
    ],
    element_weakness: 'loi',
    lore: 'Thần quy huyền minh thọ mấy vạn năm, mai chứa đựng vô số kinh văn thiên đạo.',
    deathText: 'Huyền Minh Thần Quy từ từ chìm xuống đất, mai phát ra ánh sáng huyền bí!',
  },

  // ============================================================
  // REALM 7 — Đại Thừa
  // ============================================================
  {
    id: 'dao_guardian',
    name: 'Đạo Tắc Thủ Hộ Thần', emoji: '⚖️',
    minRealm: 7, tier: 9, element: null,
    hpBase: 800000, atkBase: 20000, defBase: 10000, spdBase: 50,
    hpScale: 2.0, atkScale: 1.85,
    expReward: 35000, stoneReward: [20000, 40000],
    skills: ['law_decree', 'divine_thunder', 'heavenly_judgement', 'berserk'],
    drops: [
      { itemId: 'dao_fragment', chance: 0.50, qty: [1, 1] },
      { itemId: 'chaos_scale',  chance: 0.40, qty: [1, 2] },
      { itemId: 'heaven_stone', chance: 0.60, qty: [2, 3] },
    ],
    element_weakness: null,
    lore: 'Hiện thân của quy tắc thiên đạo, không có cảm xúc, chỉ có trọng trách bảo vệ thiên luật.',
    deathText: 'Thủ Hộ Thần tan rã thành luồng ánh sáng, trở về thiên đạo!',
  },
  {
    id: 'immortal_corpse',
    name: 'Bất Tử Tà Thi', emoji: '💀',
    minRealm: 7, tier: 9, element: 'am',
    hpBase: 1000000, atkBase: 25000, defBase: 12000, spdBase: 20,
    hpScale: 2.1, atkScale: 1.9,
    expReward: 40000, stoneReward: [25000, 50000],
    skills: ['undead_surge', 'soul_devour', 'dark_blade', 'demon_roar'],
    drops: [
      { itemId: 'immortal_bone', chance: 0.50, qty: [1, 1] },
      { itemId: 'dao_fragment',  chance: 0.35, qty: [1, 1] },
      { itemId: 'void_core',     chance: 0.55, qty: [2, 3] },
    ],
    element_weakness: 'huo',
    lore: 'Tu sĩ đại thừa không chịu đầu hàng thiên mệnh, chết rồi vẫn tiếp tục tu luyện bằng tà pháp.',
    deathText: 'Bất Tử Tà Thi rú lên thống khổ, cuối cùng được siêu thoát!',
  },
  {
    id: 'tian_luo_shen',
    name: 'Thiên La Thần', emoji: '🌟',
    minRealm: 7, tier: 9, element: 'loi',
    hpBase: 1200000, atkBase: 28000, defBase: 15000, spdBase: 45,
    hpScale: 2.05, atkScale: 1.92,
    expReward: 42000, stoneReward: [28000, 55000],
    skills: ['divine_thunder', 'heavenly_judgement', 'lightning_strike', 'berserk'],
    drops: [
      { itemId: 'dao_fragment',  chance: 0.45, qty: [1, 1] },
      { itemId: 'immortal_bone', chance: 0.40, qty: [1, 1] },
      { itemId: 'chaos_pearl',   chance: 0.25, qty: [1, 1] },
    ],
    element_weakness: 'tu',
    lore: 'Thần lôi thiên la, cai quản vạn lôi thiên đình, kẻ nào dám nghịch thiên ắt bị trừng phạt.',
    deathText: 'Thiên La Thần tan vào sấm sét, tiếng sấm vang mãi không dứt!',
  },

  // ============================================================
  // BOSS ĐẶC BIỆT — chỉ xuất hiện qua sự kiện
  // ============================================================
  {
    id: 'tian_jie_dragon',
    name: 'Thiên Lôi Thần Long', emoji: '🐉',
    minRealm: 0, tier: 10,
    hpBase: 2000, atkBase: 100, defBase: 50, spdBase: 20,
    hpScale: 2.0, atkScale: 1.8,
    expReward: 1000, stoneReward: [300, 600],
    skills: ['divine_thunder', 'dragon_breath', 'heavenly_judgement'],
    drops: [
      { itemId: 'dragon_scale', chance: 0.80, qty: [1, 2] },
      { itemId: 'heaven_stone', chance: 0.50, qty: [1, 1] },
      { itemId: 'dragon_core',  chance: 1.00, qty: [1, 1] },
    ],
    element_weakness: null,
    lore: 'Thiên đạo phái xuống để thử thách kẻ dám vượt cõi! Không thể bỏ chạy.',
    deathText: 'Thần Long rống lên, tan thành tia chớp vàng rực!',
    isBoss: true,
    canFlee: false,
  },
];

// ---- Enemy skills ----
export const ENEMY_SKILLS = {
  // Tier 1 — cơ bản
  bite:           { name: 'Cắn',              dmgMult: 1.1,  effect: null,           chance: 0.7 },
  peck:           { name: 'Mổ',               dmgMult: 1.0,  effect: null,           chance: 0.7 },
  dodge:          { name: 'Né Tránh',         dmgMult: 0,    effect: 'buff_spd',      chance: 0.3 },
  fly_dodge:      { name: 'Bay Né',           dmgMult: 0,    effect: 'buff_spd',      chance: 0.25 },
  poison_dust:    { name: 'Phun Bột Độc',     dmgMult: 0.5,  effect: 'poison',        chance: 0.5 },
  claw_strike:    { name: 'Cào Sắc',          dmgMult: 1.2,  effect: null,           chance: 0.6 },
  howl:           { name: 'Rú Hú',            dmgMult: 0,    effect: 'debuff_def15',  chance: 0.3 },
  // Tier 2 — trung cấp
  heavy_blow:     { name: 'Đòn Nặng',         dmgMult: 1.8,  effect: 'stun',          chance: 0.25 },
  stone_skin:     { name: 'Da Đá',            dmgMult: 0,    effect: 'buff_def30',    chance: 0.3 },
  tail_whip:      { name: 'Quất Đuôi',        dmgMult: 1.3,  effect: 'stun',          chance: 0.25 },
  charge:         { name: 'Húc',              dmgMult: 1.6,  effect: 'stun',          chance: 0.3 },
  fire_tusk:      { name: 'Nanh Lửa',         dmgMult: 1.4,  effect: 'burn',          chance: 0.35 },
  fire_breath:    { name: 'Thở Lửa',          dmgMult: 1.5,  effect: 'burn',          chance: 0.35 },
  agility:        { name: 'Tăng Tốc',         dmgMult: 0,    effect: 'buff_spd',      chance: 0.25 },
  dive_strike:    { name: 'Lao Từ Trên',      dmgMult: 1.5,  effect: null,            chance: 0.4 },
  wing_gust:      { name: 'Cánh Gió',         dmgMult: 0.8,  effect: 'debuff_def15',  chance: 0.3 },
  water_spit:     { name: 'Phun Nước',        dmgMult: 1.2,  effect: 'slow',          chance: 0.4 },
  slippery:       { name: 'Trơn Nhớt',        dmgMult: 0,    effect: 'buff_spd',      chance: 0.3 },
  vine_whip:      { name: 'Roi Dây Leo',      dmgMult: 1.3,  effect: 'bind',          chance: 0.35 },
  root_bind:      { name: 'Trói Rễ Cây',      dmgMult: 0,    effect: 'bind',          chance: 0.3 },
  iron_shell:     { name: 'Giáp Sắt',         dmgMult: 0,    effect: 'buff_def30',    chance: 0.3 },
  // Tier 3 — cao cấp
  lightning_strike: { name: 'Lôi Kích',       dmgMult: 2.0,  effect: 'paralyze',      chance: 0.3 },
  dive_bomb:      { name: 'Tấn Công Lao',     dmgMult: 1.6,  effect: null,            chance: 0.4 },
  thunder_cry:    { name: 'Lôi Hống',         dmgMult: 0,    effect: 'debuff_atk20',  chance: 0.2 },
  ice_fang:       { name: 'Nanh Băng',        dmgMult: 1.4,  effect: 'slow',          chance: 0.4 },
  freeze:         { name: 'Đóng Băng',        dmgMult: 0,    effect: 'freeze',        chance: 0.2 },
  coil:           { name: 'Siết Chặt',        dmgMult: 1.3,  effect: 'bind',          chance: 0.35 },
  water_cannon:   { name: 'Thủy Pháo',        dmgMult: 2.0,  effect: 'slow',          chance: 0.35 },
  shell_guard:    { name: 'Giáp Mai',         dmgMult: 0,    effect: 'buff_def30',    chance: 0.3 },
  wind_claw:      { name: 'Vuốt Gió',         dmgMult: 1.6,  effect: null,            chance: 0.4 },
  fire_charge:    { name: 'Húc Lửa',          dmgMult: 2.0,  effect: 'burn',          chance: 0.3 },
  iron_fist:      { name: 'Nắm Đấm Sắt',     dmgMult: 1.8,  effect: 'stun',          chance: 0.25 },
  // Tier 4-5
  dark_blade:     { name: 'Hắc Kiếm',         dmgMult: 2.5,  effect: null,            chance: 0.35 },
  demon_roar:     { name: 'Yêu Hống',         dmgMult: 0,    effect: 'fear',          chance: 0.2 },
  armor_break:    { name: 'Phá Giáp',         dmgMult: 1.0,  effect: 'break_armor',   chance: 0.25 },
  berserk:        { name: 'Điên Cuồng',       dmgMult: 0,    effect: 'berserk',       chance: 0.15 },
  blood_drain:    { name: 'Hút Máu',          dmgMult: 1.5,  effect: 'lifesteal',     chance: 0.4 },
  wing_slash:     { name: 'Cánh Liêm',        dmgMult: 2.0,  effect: null,            chance: 0.35 },
  venom_bite:     { name: 'Nanh Độc',         dmgMult: 1.6,  effect: 'poison',        chance: 0.4 },
  jade_scales:    { name: 'Ngọc Giáp',        dmgMult: 0,    effect: 'buff_def30',    chance: 0.25 },
  phantom_strike: { name: 'Ảo Ảnh Kích',      dmgMult: 2.5,  effect: null,            chance: 0.4 },
  illusion:       { name: 'Tạo Ảo Cảnh',      dmgMult: 0,    effect: 'debuff_def15',  chance: 0.3 },
  nine_tails:     { name: 'Cửu Vĩ Liên Kích', dmgMult: 1.8,  effect: null,            chance: 0.35 },
  fire_web:       { name: 'Lưới Lửa',         dmgMult: 1.4,  effect: 'burn',          chance: 0.35 },
  fear:           { name: 'Gieo Sợ Hãi',      dmgMult: 0,    effect: 'fear',          chance: 0.3 },
  horn_thrust:    { name: 'Đâm Sừng',         dmgMult: 2.2,  effect: 'break_armor',   chance: 0.3 },
  // Tier 6-7
  earth_quake:    { name: 'Địa Chấn',         dmgMult: 2.5,  effect: 'stun',          chance: 0.3 },
  dragon_tail:    { name: 'Long Vĩ Quét',     dmgMult: 2.0,  effect: 'debuff_def15',  chance: 0.4 },
  stone_armor:    { name: 'Thạch Giáp',       dmgMult: 0,    effect: 'buff_def30',    chance: 0.25 },
  gale_strike:    { name: 'Cuồng Phong Kích', dmgMult: 2.2,  effect: null,            chance: 0.4 },
  wind_vortex:    { name: 'Phong Xoáy',       dmgMult: 1.5,  effect: 'debuff_atk20',  chance: 0.3 },
  sonic_boom:     { name: 'Âm Thanh Sóng',    dmgMult: 3.0,  effect: 'stun',          chance: 0.2 },
  divine_thunder: { name: 'Thiên Lôi',        dmgMult: 3.0,  effect: 'paralyze',      chance: 0.3 },
  dragon_breath:  { name: 'Long Hơi',         dmgMult: 2.0,  effect: 'burn',          chance: 0.35 },
  void_slash:     { name: 'Hư Không Trảm',    dmgMult: 3.0,  effect: null,            chance: 0.35 },
  dimension_rip:  { name: 'Xé Không Gian',    dmgMult: 3.5,  effect: 'stun',          chance: 0.2 },
  blizzard:       { name: 'Tuyết Bão',        dmgMult: 2.0,  effect: 'freeze',        chance: 0.35 },
  ice_prison:     { name: 'Băng Ngục',        dmgMult: 0,    effect: 'freeze',        chance: 0.3 },
  glacier_stomp:  { name: 'Băng Hà Đạp',      dmgMult: 2.8,  effect: 'stun',          chance: 0.25 },
  // Tier 8-9
  tiger_roar:     { name: 'Hổ Hống',          dmgMult: 0,    effect: 'fear',          chance: 0.3 },
  heaven_claw:    { name: 'Thiên Trảo',        dmgMult: 4.0,  effect: 'break_armor',   chance: 0.3 },
  divine_fang:    { name: 'Thần Nha',          dmgMult: 3.5,  effect: 'burn',          chance: 0.3 },
  chaos_breath:   { name: 'Hỗn Độn Thở',      dmgMult: 3.5,  effect: 'burn',          chance: 0.3 },
  heavenly_judgement: { name: 'Thiên Phán',   dmgMult: 4.0,  effect: 'doom',          chance: 0.15 },
  law_decree:     { name: 'Thiên Luật Phán',  dmgMult: 5.0,  effect: 'doom',          chance: 0.2 },
  undead_surge:   { name: 'Tà Thi Bạo Phát',  dmgMult: 4.0,  effect: 'lifesteal',     chance: 0.3 },
  soul_devour:    { name: 'Thực Hồn',          dmgMult: 3.5,  effect: 'debuff_atk20',  chance: 0.35 },
};

// ---- Player combat skills ----
// Mở khóa theo realmIdx; cost = MP
export const COMBAT_SKILLS = [
  // ---- Realm 0: Luyện Khí ----
  {
    id: 'basic_strike',
    name: 'Phổ Thông Tấn Công', emoji: '👊',
    unlockRealm: 0, mpCost: 0, cooldown: 0,
    dmgMult: 1.0, effect: null,
    desc: 'Tấn công cơ bản không tiêu tốn linh lực.',
    combo: null,
  },
  {
    id: 'qi_burst',
    name: 'Linh Lực Bộc Phát', emoji: '💥',
    unlockRealm: 0, mpCost: 15, cooldown: 2,
    dmgMult: 1.8, effect: null,
    desc: 'Dồn linh lực vào một đòn mạnh.',
    combo: { after: 'basic_strike', bonus: 'extra_hit' },
  },
  {
    id: 'iron_guard',
    name: 'Thiết Hộ Quyết', emoji: '🛡',
    unlockRealm: 0, mpCost: 10, cooldown: 3,
    dmgMult: 0, effect: 'buff_def_self_20',
    desc: 'Vận linh lực bảo vệ thân thể, tăng phòng thủ 20% trong 2 lượt.',
    combo: null,
  },
  {
    id: 'qi_arrow',
    name: 'Khí Tiễn', emoji: '🏹',
    unlockRealm: 0, mpCost: 12, cooldown: 2,
    dmgMult: 1.5, effect: 'pierce_def',
    desc: 'Bắn mũi tên linh lực xuyên qua phòng thủ địch.',
    combo: null,
  },
  // ---- Realm 1: Trúc Cơ ----
  {
    id: 'sword_intent',
    name: 'Kiếm Ý', emoji: '⚔',
    unlockRealm: 1, mpCost: 20, cooldown: 3,
    dmgMult: 2.2, effect: 'pierce_def',
    desc: 'Kiếm ý sắc bén, xuyên giáp của địch.',
    combo: { after: 'qi_burst', bonus: 'def_break' },
  },
  {
    id: 'fire_palm',
    name: 'Hỏa Linh Chưởng', emoji: '🔥',
    unlockRealm: 1, mpCost: 25, cooldown: 3,
    dmgMult: 1.6, effect: 'burn_3turn', element: 'huo',
    desc: 'Chưởng lửa thiêng, để lại vết bỏng 3 lượt.',
    combo: null,
  },
  {
    id: 'water_shield',
    name: 'Thủy Linh Khiên', emoji: '💧',
    unlockRealm: 1, mpCost: 18, cooldown: 4,
    dmgMult: 0, effect: 'shield_2turn', element: 'thuy',
    desc: 'Tạo lá chắn nước hấp thụ một phần sát thương trong 2 lượt.',
    combo: null,
  },
  {
    id: 'earth_stomp',
    name: 'Địa Hệ Chấn Cước', emoji: '🗿',
    unlockRealm: 1, mpCost: 22, cooldown: 4,
    dmgMult: 1.9, effect: 'stun_1turn', element: 'tu',
    desc: 'Đạp chân gọi địa lực, kẻ địch choáng váng 1 lượt.',
    combo: { after: 'iron_guard', bonus: 'counter_attack' },
  },
  // ---- Realm 2: Kim Đan ----
  {
    id: 'thunder_step',
    name: 'Lôi Ảnh Bộ', emoji: '⚡',
    unlockRealm: 2, mpCost: 30, cooldown: 4,
    dmgMult: 0, effect: 'dodge_next', element: 'loi',
    desc: 'Tốc độ tăng vọt, né tránh đòn tấn công tiếp theo.',
    combo: { after: 'sword_intent', bonus: 'instant_counter' },
  },
  {
    id: 'wind_slash',
    name: 'Phong Kiếm Khí', emoji: '🌪',
    unlockRealm: 2, mpCost: 35, cooldown: 3,
    dmgMult: 2.5, effect: 'multi_hit_2', element: 'phong',
    desc: 'Kiếm khí phong hệ, chém 2 lần liên tiếp.',
    combo: { after: 'qi_arrow', bonus: 'chain_shot' },
  },
  {
    id: 'poison_seal',
    name: 'Huyền Độc Ấn', emoji: '☠',
    unlockRealm: 2, mpCost: 28, cooldown: 5,
    dmgMult: 1.2, effect: 'poison_5turn',
    desc: 'Ấn độc vào địch, nhiễm độc 5 lượt.',
    combo: null,
  },
  // ---- Realm 3: Nguyên Anh ----
  {
    id: 'dragon_claw',
    name: 'Long Hổ Thần Chưởng', emoji: '🐉',
    unlockRealm: 3, mpCost: 50, cooldown: 5,
    dmgMult: 3.5, effect: 'stun_1turn',
    desc: 'Tuyệt kỹ của đại năng, hội tụ linh lực toàn thân.',
    combo: { after: 'thunder_step', bonus: 'combo_finish' },
  },
  {
    id: 'soul_burn',
    name: 'Huyết Linh Thiêu', emoji: '🩸',
    unlockRealm: 3, mpCost: 45, cooldown: 5,
    dmgMult: 2.8, effect: 'lifesteal',
    desc: 'Thiêu đốt linh hồn địch, hút một phần sát thương thành HP.',
    combo: null,
  },
  // ---- Realm 4: Hóa Thần ----
  {
    id: 'void_blade',
    name: 'Hư Không Thần Kiếm', emoji: '🌌',
    unlockRealm: 4, mpCost: 70, cooldown: 6,
    dmgMult: 4.5, effect: 'ignore_def',
    desc: 'Kiếm từ hư không, bỏ qua hoàn toàn phòng thủ địch.',
    combo: { after: 'dragon_claw', bonus: 'void_combo' },
  },
  // ---- Realm 5: Luyện Hư ----
  {
    id: 'heaven_collapse',
    name: 'Thiên Địa Sụp Đổ', emoji: '☄',
    unlockRealm: 5, mpCost: 100, cooldown: 8,
    dmgMult: 6.0, effect: 'doom',
    desc: 'Tuyệt kỹ tối thượng — hội tụ thiên địa linh lực vào một điểm.',
    combo: null,
  },
];

// ---- Item drops lookup ----
export const ITEM_DROPS = [
  // Tier 1 drops
  { id: 'wolf_fang',      name: 'Nanh Sói Yêu',       emoji: '🦷', rarity: 'common' },
  { id: 'earth_stone',    name: 'Thổ Nguyên Thạch',   emoji: '🪨', rarity: 'common' },
  { id: 'fox_tail',       name: 'Đuôi Hồ Linh',       emoji: '🦊', rarity: 'uncommon' },
  { id: 'fire_essence',   name: 'Hỏa Tinh Hoa',       emoji: '🔥', rarity: 'uncommon' },
  { id: 'rat_fur',        name: 'Hỏa Thử Lông',       emoji: '🐀', rarity: 'common' },
  { id: 'rabbit_fur',     name: 'Linh Thỏ Lông',      emoji: '🐇', rarity: 'common' },
  { id: 'bird_feather',   name: 'Linh Tước Vũ',       emoji: '🐦', rarity: 'common' },
  { id: 'butterfly_wing', name: 'Độc Điệp Cánh',      emoji: '🦋', rarity: 'uncommon' },
  { id: 'poison_sac',     name: 'Độc Nang',            emoji: '☠',  rarity: 'uncommon' },
  { id: 'boar_tusk',      name: 'Hỏa Trư Nanh',       emoji: '🐗', rarity: 'common' },
  { id: 'stone_scale',    name: 'Thạch Bì Vảy',       emoji: '🦎', rarity: 'uncommon' },
  { id: 'eagle_claw',     name: 'Sơn Ưng Vuốt',       emoji: '🦅', rarity: 'uncommon' },
  { id: 'frog_skin',      name: 'Thủy Ếch Da',        emoji: '🐸', rarity: 'common' },
  { id: 'gold_shell',     name: 'Kim Giáp Mảnh',      emoji: '🦀', rarity: 'uncommon' },
  // Tier 2 drops
  { id: 'hawk_feather',   name: 'Lôi Ưng Vũ',         emoji: '🪶', rarity: 'uncommon' },
  { id: 'lightning_core', name: 'Lôi Tinh Hạch',      emoji: '⚡', rarity: 'rare' },
  { id: 'serpent_scale',  name: 'Băng Xà Vảy',        emoji: '🐍', rarity: 'uncommon' },
  { id: 'ice_crystal',    name: 'Băng Tinh Thể',      emoji: '❄',  rarity: 'rare' },
  { id: 'demon_core_1',   name: 'Yêu Hạch Sơ Phẩm',  emoji: '💎', rarity: 'uncommon' },
  { id: 'demon_core_2',   name: 'Yêu Hạch Trung Phẩm',emoji: '💠', rarity: 'rare' },
  { id: 'turtle_shell',   name: 'Thủy Long Mai',      emoji: '🐢', rarity: 'uncommon' },
  { id: 'wind_fur',       name: 'Phong Linh Lông',    emoji: '🐱', rarity: 'uncommon' },
  { id: 'fire_core',      name: 'Hỏa Tinh Hạch',      emoji: '🔴', rarity: 'rare' },
  { id: 'monkey_staff',   name: 'Kim Hầu Gậy',        emoji: '🐒', rarity: 'rare' },
  // Tier 3-4 drops
  { id: 'demon_core_3',   name: 'Yêu Hạch Thượng Phẩm',emoji: '🔮', rarity: 'epic' },
  { id: 'demon_armor',    name: 'Hắc Giáp Mảnh',      emoji: '🛡', rarity: 'rare' },
  { id: 'dark_essence',   name: 'Hắc Ám Tinh Hoa',    emoji: '🌑', rarity: 'rare' },
  { id: 'blood_crystal',  name: 'Huyết Tinh Thạch',   emoji: '🔴', rarity: 'rare' },
  { id: 'jade_serpent_gall', name: 'Bích Xà Đởm',     emoji: '💚', rarity: 'rare' },
  { id: 'phantom_fur',    name: 'Ảo Ảnh Hồ Mao',     emoji: '🌙', rarity: 'epic' },
  { id: 'spider_silk',    name: 'Xích Hỏa Tơ Nhện',  emoji: '🕷', rarity: 'rare' },
  { id: 'crimson_herb',   name: 'Xích Linh Thảo',     emoji: '🌺', rarity: 'rare' },
  { id: 'rhino_horn',     name: 'Thạch Tê Ngưu Sừng', emoji: '🦏', rarity: 'rare' },
  { id: 'green_scale',    name: 'Thanh Long Vảy',     emoji: '🐲', rarity: 'rare' },
  { id: 'frost_fur',      name: 'Băng Hùng Bì',       emoji: '🐻', rarity: 'rare' },
  // Tier 5-6 drops
  { id: 'earth_dragon_core', name: 'Địa Long Tinh Hạch', emoji: '🟤', rarity: 'epic' },
  { id: 'roc_feather',    name: 'Đại Bằng Thần Vũ',   emoji: '🪶', rarity: 'epic' },
  { id: 'phoenix_feather',name: 'Phượng Vũ',          emoji: '🦅', rarity: 'epic' },
  { id: 'qilin_horn',     name: 'Kỳ Lân Thiên Sừng',  emoji: '🦌', rarity: 'legendary' },
  // Tier 7-9 drops
  { id: 'void_core',      name: 'Hư Không Tinh Hạch', emoji: '🌑', rarity: 'legendary' },
  { id: 'frost_heart',    name: 'Băng Nguyên Tâm',    emoji: '💙', rarity: 'legendary' },
  { id: 'tiger_soul',     name: 'Thiên Hổ Hồn',       emoji: '🟠', rarity: 'legendary' },
  { id: 'chaos_scale',    name: 'Hỗn Độn Long Vảy',   emoji: '🌈', rarity: 'legendary' },
  { id: 'dao_fragment',   name: 'Đạo Tắc Mảnh',       emoji: '☯️', rarity: 'legendary' },
  { id: 'immortal_bone',  name: 'Bất Tử Thánh Cốt',   emoji: '🦴', rarity: 'legendary' },
  { id: 'chaos_pearl',    name: 'Hỗn Độn Minh Châu',  emoji: '🔮', rarity: 'legendary' },
  // Thảo dược & đặc biệt
  { id: 'spirit_herb',    name: 'Linh Thảo',           emoji: '🌿', rarity: 'common' },
  { id: 'jade_lotus',     name: 'Ngọc Liên',           emoji: '🪷', rarity: 'uncommon' },
  { id: 'blood_ginseng',  name: 'Huyết Sâm',           emoji: '🌱', rarity: 'rare' },
  { id: 'void_grass',     name: 'Hư Vô Thảo',          emoji: '✨', rarity: 'epic' },
  { id: 'dragon_scale',   name: 'Long Vảy Thiên Lôi',  emoji: '🐉', rarity: 'legendary' },
  { id: 'heaven_stone',   name: 'Thiên Thạch',          emoji: '☄',  rarity: 'legendary' },
  { id: 'dragon_core',    name: 'Long Hạch',            emoji: '⭐', rarity: 'legendary' },
  { id: 'immortal_root',  name: 'Tiên Căn',             emoji: '☘',  rarity: 'legendary' },
];

// ============================================================
// NGŨ HÀNH TƯƠNG KHẮC
// Kim→Mộc→Thổ→Thủy→Hỏa→Kim
// ============================================================
export const ELEMENT_ADVANTAGE = {
  kim:   { beats: 'moc',  emoji: '⚔🌿', mult: 1.3, desc: 'Kim khắc Mộc' },
  moc:   { beats: 'tu',   emoji: '🌿🗿', mult: 1.3, desc: 'Mộc khắc Thổ' },
  tu:    { beats: 'thuy', emoji: '🗿💧', mult: 1.3, desc: 'Thổ khắc Thủy' },
  thuy:  { beats: 'huo',  emoji: '💧🔥', mult: 1.3, desc: 'Thủy khắc Hỏa' },
  huo:   { beats: 'kim',  emoji: '🔥⚔', mult: 1.3, desc: 'Hỏa khắc Kim' },
  // Biến dị
  loi:   { beats: 'thuy', emoji: '⚡💧', mult: 1.4, desc: 'Lôi khắc Thủy' },
  bang:  { beats: 'moc',  emoji: '❄🌿', mult: 1.4, desc: 'Băng khắc Mộc' },
  phong: { beats: 'tu',   emoji: '🌪🗿', mult: 1.2, desc: 'Phong khắc Thổ' },
  am:    { beats: 'huo',  emoji: '🌑🔥', mult: 1.3, desc: 'Âm khắc Hỏa' },
};

export function calcElementMult(attackerElement, defenderElement) {
  if (!attackerElement || !defenderElement) return 1.0;
  const adv = ELEMENT_ADVANTAGE[attackerElement];
  if (!adv) return 1.0;
  if (adv.beats === defenderElement) return adv.mult;
  const defAdv = ELEMENT_ADVANTAGE[defenderElement];
  if (defAdv?.beats === attackerElement) return 0.75;
  return 1.0;
}

export function getPlayerElement(G) {
  if (!G.spiritData?.mainElement) return null;
  return G.spiritData.mainElement;
}