// ============================================================
// equipment/equipment-data.js — Equipment definitions
// Pure data — no imports from state or engine
// ============================================================

// rarity tier index (dùng để tính stats bonus)
export const RARITY_TIERS = {
  common:    { label: 'Phổ Thông',  color: '#aaa',    bonus: 0 },
  uncommon:  { label: 'Hiếm',       color: '#4caf50',  bonus: 1 },
  rare:      { label: 'Quý',        color: '#2196f3',  bonus: 2 },
  epic:      { label: 'Sử Thi',     color: '#9c27b0',  bonus: 3 },
  legendary: { label: 'Huyền Thoại',color: '#ff9800',  bonus: 4 },
};

// slot: 'weapon' | 'armor' | 'accessory'
// statsBase: stats ở rarity common
// statsPerRarity: stats cộng thêm mỗi bậc rarity
export const EQUIPMENT = [
  // ============ WEAPONS ============
  {
    id: 'wood_staff',
    name: 'Gậy Gỗ Linh',
    emoji: '🪄',
    slot: 'weapon',
    rarity: 'common',
    minRealm: 0,
    statsBase: { atk: 8 },
    statsPerRarity: { atk: 5 },
    dropFrom: [],
    dropChance: 0,
    lore: 'Gậy gỗ thô sơ, vũ khí đầu tay của người mới nhập môn. Không có gì đặc biệt, nhưng đủ để tự vệ.',
    starterOnly: true, // chỉ xuất hiện khi khởi đầu game
  },
  {
    id: 'iron_sword',
    name: 'Thiết Kiếm',
    emoji: '⚔',
    slot: 'weapon',
    rarity: 'common',
    minRealm: 0,
    statsBase: { atk: 12 },
    statsPerRarity: { atk: 8 },
    dropFrom: ['demon_wolf', 'stone_golem'],
    dropChance: 0.08,
    lore: 'Kiếm sắt thường dùng của môn phái nhỏ.',
  },
  {
    id: 'thunder_blade',
    name: 'Lôi Linh Kiếm',
    emoji: '⚡',
    slot: 'weapon',
    rarity: 'uncommon',
    minRealm: 1,
    statsBase: { atk: 40, atkPct: 5 },
    statsPerRarity: { atk: 20, atkPct: 3 },
    dropFrom: ['thunder_hawk'],
    dropChance: 0.10,
    lore: 'Kiếm rèn từ lôi tinh, mỗi nhát chém kèm theo sấm chớp.',
  },
  {
    id: 'ice_spear',
    name: 'Băng Hà Thương',
    emoji: '🔱',
    slot: 'weapon',
    rarity: 'rare',
    minRealm: 1,
    statsBase: { atk: 60, atkPct: 8 },
    statsPerRarity: { atk: 30, atkPct: 5 },
    dropFrom: ['ice_serpent'],
    dropChance: 0.08,
    lore: 'Thương luyện từ băng ngàn năm, vết thương không thể lành trong giá lạnh.',
  },
  {
    id: 'demon_saber',
    name: 'Hắc Yêu Đao',
    emoji: '🗡',
    slot: 'weapon',
    rarity: 'rare',
    minRealm: 2,
    statsBase: { atk: 120, atkPct: 12 },
    statsPerRarity: { atk: 60, atkPct: 7 },
    dropFrom: ['demon_general'],
    dropChance: 0.12,
    lore: 'Đao luyện từ xương yêu tướng, thấm đẫm sát khí ngàn năm.',
  },
  {
    id: 'jade_sword',
    name: 'Bích Ngọc Kiếm',
    emoji: '💚',
    slot: 'weapon',
    rarity: 'epic',
    minRealm: 3,
    statsBase: { atk: 350, atkPct: 20 },
    statsPerRarity: { atk: 150, atkPct: 10 },
    dropFrom: ['jade_serpent', 'phantom_fox'],
    dropChance: 0.07,
    lore: 'Kiếm đúc từ ngọc linh xà, có thể cắt đứt cả không gian.',
  },
  {
    id: 'earth_dragon_axe',
    name: 'Địa Long Phủ',
    emoji: '🪓',
    slot: 'weapon',
    rarity: 'epic',
    minRealm: 4,
    statsBase: { atk: 900, atkPct: 25 },
    statsPerRarity: { atk: 400, atkPct: 12 },
    dropFrom: ['earth_dragon'],
    dropChance: 0.08,
    lore: 'Phủ đúc từ xương Địa Long, nặng như ngọn núi mà nhẹ trong tay đại năng.',
  },
  {
    id: 'void_blade',
    name: 'Hư Không Thần Kiếm',
    emoji: '🌑',
    slot: 'weapon',
    rarity: 'legendary',
    minRealm: 5,
    statsBase: { atk: 2500, atkPct: 40 },
    statsPerRarity: { atk: 1000, atkPct: 20 },
    dropFrom: ['void_demon', 'frost_giant'],
    dropChance: 0.05,
    lore: 'Kiếm sinh từ hư không, vô hình vô tướng, chỉ ý chí của chủ nhân mới điều khiển được.',
  },
  {
    id: 'chaos_dragon_sword',
    name: 'Hỗn Độn Long Kiếm',
    emoji: '🐲',
    slot: 'weapon',
    rarity: 'legendary',
    minRealm: 6,
    statsBase: { atk: 8000, atkPct: 60 },
    statsPerRarity: { atk: 3000, atkPct: 25 },
    dropFrom: ['chaos_wyrm'],
    dropChance: 0.06,
    lore: 'Kiếm đúc từ vảy Hỗn Độn Thần Long, mang hỗn độn khí từ thủa khai thiên tịch địa.',
  },

  // ============ ARMOR ============
  {
    id: 'leather_vest',
    name: 'Bì Giáp',
    emoji: '🦺',
    slot: 'armor',
    rarity: 'common',
    minRealm: 0,
    statsBase: { def: 8, hp: 50 },
    statsPerRarity: { def: 5, hp: 30 },
    dropFrom: ['demon_wolf', 'fire_fox'],
    dropChance: 0.08,
    lore: 'Giáp da thú đơn giản, chỉ đủ chống lại đòn thường.',
  },
  {
    id: 'stone_shell',
    name: 'Thổ Nguyên Giáp',
    emoji: '🗿',
    slot: 'armor',
    rarity: 'uncommon',
    minRealm: 0,
    statsBase: { def: 25, hp: 150, defPct: 5 },
    statsPerRarity: { def: 15, hp: 80, defPct: 3 },
    dropFrom: ['stone_golem'],
    dropChance: 0.10,
    lore: 'Giáp đất cứng như thạch anh, nặng nhưng bền.',
  },
  {
    id: 'serpent_mail',
    name: 'Băng Xà Giáp',
    emoji: '🐍',
    slot: 'armor',
    rarity: 'rare',
    minRealm: 1,
    statsBase: { def: 60, hp: 400, defPct: 10 },
    statsPerRarity: { def: 30, hp: 200, defPct: 5 },
    dropFrom: ['ice_serpent'],
    dropChance: 0.08,
    lore: 'Giáp từ vảy băng xà, lạnh tỏa khắp thân, tự động giải độc và chống lạnh.',
  },
  {
    id: 'demon_plate',
    name: 'Hắc Yêu Trọng Giáp',
    emoji: '🛡',
    slot: 'armor',
    rarity: 'rare',
    minRealm: 2,
    statsBase: { def: 150, hp: 1000, defPct: 15 },
    statsPerRarity: { def: 70, hp: 500, defPct: 8 },
    dropFrom: ['demon_general'],
    dropChance: 0.10,
    lore: 'Trọng giáp của Yêu Tướng, đen tuyền như đêm, thấm nhuần sát khí.',
  },
  {
    id: 'phantom_robe',
    name: 'Ảo Ảnh Linh Bào',
    emoji: '🌙',
    slot: 'armor',
    rarity: 'epic',
    minRealm: 3,
    statsBase: { def: 300, hp: 3000, hpPct: 15 },
    statsPerRarity: { def: 150, hp: 1500, hpPct: 8 },
    dropFrom: ['phantom_fox', 'blood_bat'],
    dropChance: 0.07,
    lore: 'Bào từ lông Cửu Vĩ Hồ, nhẹ như không khí, có thể tạo ảo ảnh phân thân.',
  },
  {
    id: 'earth_dragon_scale',
    name: 'Địa Long Lân Giáp',
    emoji: '🟤',
    slot: 'armor',
    rarity: 'epic',
    minRealm: 4,
    statsBase: { def: 800, hp: 8000, defPct: 20 },
    statsPerRarity: { def: 400, hp: 4000, defPct: 10 },
    dropFrom: ['earth_dragon'],
    dropChance: 0.07,
    lore: 'Giáp rèn từ vảy Địa Long, cứng tuyệt đối, không kiếm pháp nào phá được.',
  },
  {
    id: 'void_armor',
    name: 'Hư Không Thần Giáp',
    emoji: '🌑',
    slot: 'armor',
    rarity: 'legendary',
    minRealm: 5,
    statsBase: { def: 2000, hp: 20000, defPct: 30, hpPct: 20 },
    statsPerRarity: { def: 800, hp: 8000, defPct: 15, hpPct: 10 },
    dropFrom: ['void_demon'],
    dropChance: 0.05,
    lore: 'Giáp đúc từ hư không, có thể hấp thụ một phần sát thương về hư vô.',
  },
  {
    id: 'tiger_battle_armor',
    name: 'Thiên Hổ Chiến Giáp',
    emoji: '🐅',
    slot: 'armor',
    rarity: 'legendary',
    minRealm: 6,
    statsBase: { def: 6000, hp: 60000, defPct: 40, hpPct: 30 },
    statsPerRarity: { def: 2500, hp: 25000, defPct: 20, hpPct: 15 },
    dropFrom: ['celestial_tiger'],
    dropChance: 0.06,
    lore: 'Giáp đúc từ da Thiên Hổ Thần Vương, uy phong tự phát, nhìn đã khiếp vía.',
  },

  // ============ ACCESSORIES ============
  {
    id: 'qi_ring',
    name: 'Tụ Linh Nhẫn',
    emoji: '💍',
    slot: 'accessory',
    rarity: 'common',
    minRealm: 0,
    statsBase: { atkPct: 5 },
    statsPerRarity: { atkPct: 4 },
    dropFrom: ['fire_fox'],
    dropChance: 0.06,
    lore: 'Nhẫn đơn giản có tác dụng tụ linh, tăng cường linh lực luyện tập.',
  },
  {
    id: 'hawk_talisman',
    name: 'Lôi Ưng Bùa Hộ',
    emoji: '🪶',
    slot: 'accessory',
    rarity: 'uncommon',
    minRealm: 1,
    statsBase: { atkPct: 12, defPct: 5 },
    statsPerRarity: { atkPct: 8, defPct: 3 },
    dropFrom: ['thunder_hawk'],
    dropChance: 0.09,
    lore: 'Lông ưng thiêng được phù lục hóa thành bùa hộ, tăng tốc phản xạ.',
  },
  {
    id: 'blood_jade_pendant',
    name: 'Huyết Ngọc Bội',
    emoji: '🔴',
    slot: 'accessory',
    rarity: 'rare',
    minRealm: 3,
    statsBase: { hpPct: 20, defPct: 10 },
    statsPerRarity: { hpPct: 10, defPct: 5 },
    dropFrom: ['blood_bat'],
    dropChance: 0.08,
    lore: 'Ngọc máu của ma thú cổ xưa, người đeo sẽ hồi phục HP nhanh hơn.',
  },
  {
    id: 'roc_wing_charm',
    name: 'Đại Bằng Dực Phù',
    emoji: '🪶',
    slot: 'accessory',
    rarity: 'epic',
    minRealm: 4,
    statsBase: { atkPct: 30, defPct: 15 },
    statsPerRarity: { atkPct: 15, defPct: 8 },
    dropFrom: ['wind_roc'],
    dropChance: 0.07,
    lore: 'Lông Đại Bằng kết thành phù, người đeo nhẹ nhàng phi phàm như gió.',
  },
  {
    id: 'frost_heart_gem',
    name: 'Băng Tâm Châu',
    emoji: '💙',
    slot: 'accessory',
    rarity: 'epic',
    minRealm: 5,
    statsBase: { hpPct: 35, defPct: 20 },
    statsPerRarity: { hpPct: 18, defPct: 10 },
    dropFrom: ['frost_giant'],
    dropChance: 0.07,
    lore: 'Trái tim băng hóa thành châu, người đeo có thể chống lại mọi loại hỏa độc.',
  },
  {
    id: 'dao_seal',
    name: 'Đạo Ấn Thần Phù',
    emoji: '☯️',
    slot: 'accessory',
    rarity: 'legendary',
    minRealm: 7,
    statsBase: { atkPct: 60, defPct: 40, hpPct: 40 },
    statsPerRarity: { atkPct: 25, defPct: 20, hpPct: 20 },
    dropFrom: ['dao_guardian', 'immortal_corpse'],
    dropChance: 0.05,
    lore: 'Mảnh ấn từ thiên đạo, người đeo được thiên đạo nhận ra, vạn pháp không xâm.',
  },
];

// ============================================================
// TRANG BỊ MỞ RỘNG — 9 SLOTS
// ============================================================
export const EQUIPMENT_SLOTS = {
  dau:       { label: 'Đầu',       emoji: '🪖', statPrimary: 'def',   desc: 'Mũ, Quan, Khăn Tu Sĩ' },
  than:      { label: 'Thân',      emoji: '👘', statPrimary: 'def',   desc: 'Áo Giáp, Bào Phục' },
  tay_trai:  { label: 'Tay Trái',  emoji: '🛡', statPrimary: 'def',   desc: 'Khiên, Pháp Ấn, Vũ Khí Phụ' },
  tay_phai:  { label: 'Tay Phải',  emoji: '⚔',  statPrimary: 'atk',   desc: 'Vũ Khí Chính' },
  that_lung:  { label: 'Thắt Lưng',emoji: '🔑', statPrimary: 'hp',    desc: 'Đai, Túi Càn Khôn' },
  chan:      { label: 'Chân',      emoji: '👟', statPrimary: 'spdBonus', desc: 'Giày, Hài, Pháp Hài' },
  nhan_trai: { label: 'Nhẫn (T)',  emoji: '💍', statPrimary: 'atkPct',desc: 'Nhẫn Pháp Bảo Trái' },
  nhan_phai: { label: 'Nhẫn (P)',  emoji: '💍', statPrimary: 'defPct',desc: 'Nhẫn Pháp Bảo Phải' },
  phap_bao:  { label: 'Pháp Bảo',  emoji: '✨', statPrimary: 'ratePct',desc: 'Phi Kiếm, Linh Bài, Ấn' },
};

// Equipment mở rộng theo slot mới
export const EQUIPMENT_EXTENDED = [
  // === ĐẦU ===
  { id:'cloth_hat',    name:'Vải Khăn Tu',   emoji:'🪖', slot:'dau',      rarity:'common',   minRealm:0,
    statsBase:{def:5},  statsPerRarity:{def:4},
    lore:'Khăn vải thường của tu sĩ nhập môn.' },
  { id:'spirit_crown', name:'Linh Vương Quan',emoji:'👑', slot:'dau',      rarity:'rare',     minRealm:2,
    statsBase:{def:20,ratePct:5}, statsPerRarity:{def:15,ratePct:3},
    lore:'Quan mũ chứa linh khí, tăng tốc tu luyện.' },
  // === CỔ ===
  { id:'jade_pendant', name:'Ngọc Bội Linh', emoji:'📿', slot:'co',       rarity:'uncommon', minRealm:0,
    statsBase:{ratePct:3,hp:30}, statsPerRarity:{ratePct:2,hp:20},
    lore:'Ngọc bội linh thiêng, người tu luyện hay đeo.' },
  { id:'dragon_amulet',name:'Long Hình Bội',  emoji:'🐉', slot:'co',       rarity:'epic',     minRealm:3,
    statsBase:{ratePct:10,atkPct:8,hp:200}, statsPerRarity:{ratePct:5,atkPct:5,hp:100},
    lore:'Bội ngọc chạm hình rồng, truyền thuyết từ thời cổ đại.' },
  // === THÂN ===
  { id:'starter_robe',  name:'Áo Vải Thô',    emoji:'👕', slot:'than',     rarity:'common',   minRealm:0,
    statsBase:{}, statsPerRarity:{},
    noStats: true, starterOnly: true,
    lore:'Áo vải thô sơ của người mới bắt đầu tu luyện. Không có buff gì, chỉ để giữ ấm và che thân.' },
  { id:'cloth_robe',   name:'Vải Bào Phục',  emoji:'👘', slot:'than',     rarity:'common',   minRealm:0,
    statsBase:{def:8,hp:20}, statsPerRarity:{def:6,hp:15},
    lore:'Bào phục vải thường, nhẹ nhưng ít bảo vệ.' },
  { id:'spirit_armor', name:'Linh Giáp',      emoji:'🛡', slot:'than',     rarity:'rare',     minRealm:1,
    statsBase:{def:35,hp:100}, statsPerRarity:{def:25,hp:60},
    lore:'Giáp được luyện từ kim loại linh, bền hơn sắt thường.' },
  { id:'void_robe',    name:'Hư Không Bào',   emoji:'🌌', slot:'than',     rarity:'legendary',minRealm:4,
    statsBase:{def:80,hp:500,defPct:15}, statsPerRarity:{def:50,hp:300,defPct:8},
    lore:'Bào phục từ vải hư không, nhẹ như không khí mà cứng hơn mọi giáp.' },
  // === TAY TRÁI (Khiên/Ấn) ===
  { id:'wood_shield',  name:'Mộc Khiên',      emoji:'🛡', slot:'tay_trai', rarity:'common',   minRealm:0,
    statsBase:{def:6}, statsPerRarity:{def:5},
    lore:'Khiên gỗ linh đơn giản.' },
  { id:'spell_seal',   name:'Pháp Ấn Linh',   emoji:'🔯', slot:'tay_trai', rarity:'uncommon', minRealm:1,
    statsBase:{ratePct:5,def:10}, statsPerRarity:{ratePct:4,def:8},
    lore:'Pháp ấn giúp vận chuyển linh khí hiệu quả hơn.' },
  // === TAY PHẢI (Vũ khí) — đã có, thêm vài cái mới ===
  { id:'linh_kiep_sword', name:'Linh Kiếp Kiếm',emoji:'⚔', slot:'tay_phai',rarity:'epic',    minRealm:2,
    statsBase:{atk:120,atkPct:15}, statsPerRarity:{atk:80,atkPct:10},
    lore:'Kiếm rèn từ thiên lôi và long vảy, kiếm khí bất tán.' },
  // === THẮT LƯNG ===
  { id:'leather_belt', name:'Đai Da Linh',     emoji:'🔑', slot:'that_lung',rarity:'common',  minRealm:0,
    statsBase:{hp:40}, statsPerRarity:{hp:30},
    lore:'Đai da linh thú, tăng thể lực.' },
  { id:'storage_belt', name:'Đai Túi Càn Khôn',emoji:'💼', slot:'that_lung',rarity:'rare',    minRealm:1,
    statsBase:{hp:80,stoneBonus:0.5}, statsPerRarity:{hp:50,stoneBonus:0.3},
    lore:'Đai có túi càn khôn thu nhỏ, tăng khả năng mang vật phẩm.' },
  // === CHÂN ===
  { id:'straw_sandal', name:'Hài Cỏ Thô',      emoji:'👟', slot:'chan',      rarity:'common',  minRealm:0,
    statsBase:{spdBonus:0.03}, statsPerRarity:{spdBonus:0.02},
    lore:'Hài cỏ thô sơ, đi nhẹ chân hơn giày bình thường.' },
  { id:'wind_boots',   name:'Phong Hành Hài',   emoji:'🥾', slot:'chan',      rarity:'uncommon',minRealm:1,
    statsBase:{spdBonus:0.08, def:8}, statsPerRarity:{spdBonus:0.05, def:5},
    lore:'Hài luyện từ da thú phong, bước đi nhanh như gió.' },
  { id:'cloud_steps',  name:'Lăng Không Bộ',    emoji:'☁',  slot:'chan',      rarity:'rare',    minRealm:2,
    statsBase:{spdBonus:0.15, def:15, hp:60}, statsPerRarity:{spdBonus:0.08, def:10, hp:40},
    lore:'Bí kỹ đi trên không trung, kết hợp với giày linh đặc biệt.' },
  { id:'void_treads',  name:'Hư Không Thiên Hài',emoji:'🌌',slot:'chan',      rarity:'legendary',minRealm:4,
    statsBase:{spdBonus:0.3, def:40, hp:200, defPct:8}, statsPerRarity:{spdBonus:0.1, def:20, hp:100, defPct:5},
    lore:'Hài dệt từ vải hư không, người mang như đứng ngoài vũ trụ.' },
  // === NHẪN ===
  { id:'speed_ring',   name:'Nhẫn Tốc Linh',  emoji:'💍', slot:'nhan_trai',rarity:'uncommon',minRealm:0,
    statsBase:{spdBonus:0.1,ratePct:3}, statsPerRarity:{spdBonus:0.05,ratePct:2},
    lore:'Nhẫn ngọc xanh, vận chuyển linh khí nhanh hơn.' },
  { id:'power_ring',   name:'Nhẫn Lực Thần',  emoji:'💍', slot:'nhan_phai',rarity:'uncommon',minRealm:0,
    statsBase:{atkPct:5,defPct:3}, statsPerRarity:{atkPct:4,defPct:2},
    lore:'Nhẫn ngọc đỏ, ngưng tụ lực lượng.' },
  { id:'void_ring',    name:'Nhẫn Hư Không',  emoji:'🌀', slot:'nhan_trai',rarity:'legendary',minRealm:3,
    statsBase:{ratePct:15,spdBonus:0.3}, statsPerRarity:{ratePct:10,spdBonus:0.2},
    lore:'Nhẫn từ hư không, người đeo như hoà mình vào thiên đạo.' },
  // === PHÁP BẢO ===
  { id:'flying_sword', name:'Phi Kiếm Linh',  emoji:'🗡', slot:'phap_bao', rarity:'uncommon',minRealm:0,
    statsBase:{atkPct:8}, statsPerRarity:{atkPct:6},
    lore:'Phi kiếm tự vận hành, tự động tấn công trong chiến đấu.' },
  { id:'spirit_badge', name:'Hộ Thân Linh Bài',emoji:'🔵', slot:'phap_bao', rarity:'rare',   minRealm:1,
    statsBase:{defPct:10,hp:150}, statsPerRarity:{defPct:7,hp:100},
    lore:'Linh bài hộ thân, tự động kích hoạt khiên bảo vệ khi nguy hiểm.' },
  { id:'luck_charm',   name:'Duyên Khởi Linh Bài',emoji:'🍀',slot:'phap_bao',rarity:'rare',  minRealm:0,
    statsBase:{ratePct:5}, statsPerRarity:{ratePct:4},
    effect:'luck_boost',
    lore:'Linh bài cơ duyên, tăng tỷ lệ gặp kỳ ngộ khi thám hiểm.' },
];

// Pháp bảo chỉ rèn được (import từ crafting-data để dùng chung)
// Khi cần: import { CRAFTABLE_EQUIPMENT } from '../alchemy/crafting-data.js'