// ============================================================
// sect/sect-data.js — Hoạt động tông môn
// v2 — Thêm: NPC trưởng lão, dialogue, thêm đóng góp, sự kiện tông chiến
// Pure data — không import state
// ============================================================

// ---- Đóng góp tông môn ----
export const SECT_CONTRIBUTIONS = [
  {
    id: 'donate_stone',
    name: 'Cúng Nạp Linh Thạch',
    emoji: '💎',
    desc: 'Hiến dâng linh thạch để đổi lấy công lao tông môn.',
    cost: { stone: 100 },
    reward: { sectExp: 50, desc: '+50 công lao' },
    cooldown: 0,
    minRealm: 0,
  },
  {
    id: 'donate_stone_large',
    name: 'Đại Nạp Linh Thạch',
    emoji: '💎',
    desc: 'Hiến dâng số lượng lớn linh thạch, được trưởng lão ghi nhớ.',
    cost: { stone: 1000 },
    reward: { sectExp: 600, qi: 500, desc: '+600 công lao, +500 linh lực' },
    cooldown: 3600,
    minRealm: 1,
  },
  {
    id: 'donate_qi',
    name: 'Truyền Công Trợ Luyện',
    emoji: '🌬',
    desc: 'Truyền linh lực giúp đệ tử huynh đệ tu luyện.',
    cost: { qi: 500 },
    reward: { sectExp: 30, stone: 20, desc: '+30 công lao, +20 linh thạch' },
    cooldown: 0,
    minRealm: 0,
  },
  {
    id: 'patrol_mission',
    name: 'Tuần Tra Tông Môn',
    emoji: '👁',
    desc: 'Tuần tra lãnh thổ tông môn, bảo vệ huynh đệ khỏi yêu thú.',
    cost: { stamina: 30 },
    reward: { sectExp: 80, stone: 50, desc: '+80 công lao, +50 linh thạch' },
    cooldown: 300,
    minRealm: 0,
  },
  {
    id: 'patrol_mission_elite',
    name: 'Tuần Tra Sâu Giới',
    emoji: '⚔',
    desc: 'Tuần tra vùng nguy hiểm bên ngoài lãnh thổ, tiêu diệt yêu thú cấp cao.',
    cost: { stamina: 60, stone: 200 },
    reward: { sectExp: 250, stone: 150, exp: 500, desc: '+250 công lao, +150 linh thạch, +500 EXP' },
    cooldown: 1800,
    minRealm: 2,
  },
  {
    id: 'alchemy_contribution',
    name: 'Cung Cấp Đan Dược',
    emoji: '⚗',
    desc: 'Luyện đan cung cấp cho tông môn để đổi lấy công lao cao.',
    cost: { stone: 200 },
    reward: { sectExp: 150, qi: 300, desc: '+150 công lao, +300 linh lực' },
    cooldown: 600,
    minRealm: 1,
  },
  {
    id: 'alchemy_rare_pill',
    name: 'Tiến Cống Quý Đan',
    emoji: '🔮',
    desc: 'Dâng lên trưởng lão một viên đan quý, được khen thưởng hậu hĩnh.',
    cost: { stone: 800 },
    reward: { sectExp: 500, stone: 300, ratePct: 2, desc: '+500 công lao, +300 linh thạch, +2% tu luyện' },
    cooldown: 7200,
    minRealm: 2,
  },
  {
    id: 'defend_sect',
    name: 'Bảo Vệ Tông Môn',
    emoji: '🛡',
    desc: 'Đứng canh gác ải quan tông môn, đẩy lui kẻ địch.',
    cost: { stone: 500 },
    reward: { sectExp: 300, stone: 100, titleUnlock: 'sect_guardian', desc: '+300 công lao, +100 linh thạch' },
    cooldown: 3600,
    minRealm: 2,
  },
  {
    id: 'elder_lecture',
    name: 'Thụ Giáo Trưởng Lão',
    emoji: '📚',
    desc: 'Thụ giáo từ trưởng lão trong tông, thu được thần thức khai sáng.',
    cost: { stone: 1000 },
    reward: { sectExp: 500, expBonus: 10, desc: '+500 công lao, +10% kinh nghiệm trong 30 phút' },
    cooldown: 7200,
    minRealm: 3,
  },
  {
    id: 'tong_chien_support',
    name: 'Tham Gia Tông Chiến',
    emoji: '⚔',
    desc: 'Xung phong vào tuyến đầu trong tông chiến, lập công lớn.',
    cost: { stamina: 80, stone: 1000 },
    reward: { sectExp: 1000, stone: 500, atkPct: 3, desc: '+1000 công lao, +500 linh thạch, +3% ATK vĩnh viễn' },
    cooldown: 86400,
    minRealm: 3,
  },
  {
    id: 'explore_for_sect',
    name: 'Khám Phá Vì Tông Môn',
    emoji: '🗺',
    desc: 'Thám hiểm vùng đất mới thay tông môn, thu thập thông tin và nguyên liệu.',
    cost: { stamina: 40 },
    reward: { sectExp: 120, stone: 80, desc: '+120 công lao, +80 linh thạch' },
    cooldown: 900,
    minRealm: 1,
  },
];

// ---- Cấp độ tông môn ----
export const SECT_RANKS = [
  { rank: 0, name: 'Ngoại Môn Đệ Tử',  emoji: '🔘',  expRequired: 0,      bonus: null },
  { rank: 1, name: 'Nội Môn Đệ Tử',    emoji: '⭐',   expRequired: 500,    bonus: { stoneBonus: 0.5, desc: '+0.5 linh thạch/s' } },
  { rank: 2, name: 'Chân Truyền Đệ Tử',emoji: '⭐⭐',  expRequired: 2000,   bonus: { ratePct: 5, desc: '+5% tốc độ tu luyện' } },
  { rank: 3, name: 'Chấp Sự',          emoji: '⭐⭐⭐', expRequired: 5000,   bonus: { atkPct: 10, desc: '+10% công kích' } },
  { rank: 4, name: 'Hộ Pháp',          emoji: '🌟',  expRequired: 12000,  bonus: { defPct: 15, hpPct: 10, desc: '+15% phòng thủ, +10% HP' } },
  { rank: 5, name: 'Trưởng Lão',       emoji: '✨',   expRequired: 30000,  bonus: { ratePct: 20, stoneBonus: 2, desc: '+20% tu luyện, +2 linh thạch/s' } },
  { rank: 6, name: 'Phó Chưởng Môn',   emoji: '👑',  expRequired: 80000,  bonus: { atkPct: 25, defPct: 25, desc: '+25% công kích, +25% phòng thủ' } },
  { rank: 7, name: 'Chưởng Môn',       emoji: '🔥',  expRequired: 200000, bonus: { ratePct: 50, atkPct: 50, stoneBonus: 5, desc: 'Bonus tối đa của tông môn' } },
];

// ---- NPC Trưởng Lão & Huynh Đệ ----
// Mỗi tông môn có nhân vật riêng — dùng sectId để lọc
export const SECT_NPCS = [
  // === Thanh Vân Kiếm Tông ===
  {
    id: 'elder_qingyun_sword',
    name: 'Thanh Vân Kiếm Lão',
    emoji: '🧙',
    sectId: 'kiem_tong',
    role: 'trưởng lão kiếm pháp',
    minRank: 0,
    desc: 'Trưởng lão phụ trách kiếm pháp, mái tóc trắng như tuyết, kiếm khí toát ra không ngừng.',
    dialogues: [
      { id: 'greet', text: 'Kiếm đạo vô cực, chỉ có dám tiến mới có thể trở thành cường giả thực sự.' },
      { id: 'advice_realm0', text: 'Ngươi mới vào môn, hãy luyện kiếm mỗi ngày. Không có căn cơ vững chắc, cao tầng chỉ là lâu đài trên cát.', unlockRealm: 0 },
      { id: 'advice_realm1', text: 'Trúc Cơ rồi à? Tốt. Từ giờ hãy học cảm nhận kiếm ý, không chỉ là sức mạnh thuần túy.', unlockRealm: 1 },
      { id: 'advice_realm2', text: 'Kim Đan thành rồi — đây là nơi nhiều người dừng lại. Nhưng ta biết ngươi sẽ không.', unlockRealm: 2 },
      { id: 'quest_give', text: 'Ta có một nhiệm vụ muốn giao cho ngươi. Tiêu diệt đàn yêu thú đang quấy phá phía đông lãnh thổ tông.', minRank: 1 },
      { id: 'praise', text: 'Ngươi đã trưởng thành nhiều. Ta nhớ ngày đầu ngươi vào môn, kiếm cầm còn run.', minRank: 3 },
    ],
  },
  {
    id: 'junior_ling_feng',
    name: 'Sư Đệ Lăng Phong',
    emoji: '🧑',
    sectId: 'kiem_tong',
    role: 'sư đệ đồng môn',
    minRank: 0,
    desc: 'Đệ tử trẻ tuổi nhất được nhận vào cùng lúc với ngươi, tinh nghịch và thông minh.',
    dialogues: [
      { id: 'greet', text: 'Sư huynh/tỷ! Hôm nay tập kiếm chưa? Ta vừa ngộ được một chiêu mới đấy!' },
      { id: 'chat_1', text: 'Nghe nói Vạn Linh Thị vừa có buổi đấu giá lớn. Ngươi có muốn đi không?' },
      { id: 'chat_2', text: 'Hôm qua ta đánh lại Yêu Sói Đen ba lần, thua cả ba... Kiếm đạo thật khó.', unlockRealm: 0 },
      { id: 'congratulate', text: 'Sư huynh/tỷ đạt Trúc Cơ rồi! Ta còn phải cố gắng nhiều hơn nữa...', unlockRealm: 1 },
      { id: 'rival', text: 'Ta không thua ngươi đâu nhé! Chờ ta đạt Kim Đan, chúng ta sẽ tỷ thí một trận!', unlockRealm: 2 },
    ],
  },
  {
    id: 'senior_yun_xiao',
    name: 'Sư Tỷ Vân Tiêu',
    emoji: '👩',
    sectId: 'kiem_tong',
    role: 'sư tỷ cao cấp',
    minRank: 1,
    desc: 'Thiên tài bậc nhất Thanh Vân Kiếm Tông thế hệ này, luôn ở trước ngươi một bước.',
    dialogues: [
      { id: 'greet', text: 'Ngươi lại đến rồi. Công lực tiến bộ đó, nhưng vẫn còn cách ta một đoạn dài.' },
      { id: 'advice', text: 'Đừng chỉ chú tâm vào sức mạnh. Kiếm tâm mới là cốt lõi của Thanh Vân Kiếm Tông.', minRank: 2 },
      { id: 'secret', text: '...Thật ra ta cũng đang gặp khó khăn với Kim Đan đột phá. Nhưng đừng nói với ai.', unlockRealm: 2 },
      { id: 'respect', text: 'Hmm. Lần này ta phải thừa nhận — ngươi đã trưởng thành thật sự.', minRank: 4 },
    ],
  },

  // === Vạn Linh Đan Tông ===
  {
    id: 'elder_wanling_dan',
    name: 'Vạn Linh Đan Lão',
    emoji: '🧙',
    sectId: 'dan_tong',
    role: 'trưởng lão đan đạo',
    minRank: 0,
    desc: 'Đại đan sư của Vạn Linh Đan Tông, tóc bạc phơ nhưng đôi mắt sắc như kiếm.',
    dialogues: [
      { id: 'greet', text: 'Lửa đan không bao giờ nói dối. Ngươi thành công hay thất bại — đan lò biết tất cả.' },
      { id: 'advice_realm0', text: 'Bắt đầu với Tụ Linh Đan. Đừng vội vàng. Hiểu lửa đan trước, rồi mới nghĩ đến đan phẩm cao hơn.', unlockRealm: 0 },
      { id: 'advice_realm1', text: 'Ngươi đã có Trúc Cơ, linh lực ổn định hơn. Lúc này luyện đan Tier 2 sẽ dễ hơn nhiều.', unlockRealm: 1 },
      { id: 'secret_recipe', text: 'Ta có một công thức bí mật truyền qua ba đời. Ngươi đủ duyên mới được nghe...', minRank: 3 },
      { id: 'praise', text: 'Một trăm lần luyện đan. Ta đã trải qua con đường này — ta hiểu sự vất vả của ngươi.', minRank: 4 },
    ],
  },
  {
    id: 'junior_dan_mei',
    name: 'Sư Muội Đan Mai',
    emoji: '👧',
    sectId: 'dan_tong',
    role: 'sư muội đồng môn',
    minRank: 0,
    desc: 'Đệ tử nhỏ tuổi nhất, mê đắm đan đạo đến quên ăn quên ngủ.',
    dialogues: [
      { id: 'greet', text: 'Ồ sư huynh/tỷ! Hôm nay luyện đan chưa? Em vừa luyện được Hồi Nguyên Đan rồi!' },
      { id: 'share', text: 'Em tìm được bãi Bạch Ngọc Liên ở phía bắc! Nhưng đừng nói với ai nhé, để em thu thêm đã.' },
      { id: 'help', text: 'Sư huynh/tỷ có dư nguyên liệu không? Em thiếu Linh Thảo mà không tìm được...', unlockRealm: 0 },
      { id: 'dream', text: 'Ước mơ của em là luyện được Thiên Địa Hóa Nguyên Đan một lần trong đời. Sư huynh/tỷ nghĩ em có làm được không?', unlockRealm: 1 },
    ],
  },
  {
    id: 'senior_bai_yao',
    name: 'Sư Huynh Bạch Diệu',
    emoji: '👨',
    sectId: 'dan_tong',
    role: 'sư huynh cao cấp',
    minRank: 1,
    desc: 'Đệ tử xuất sắc nhất thế hệ trước của Vạn Linh Đan Tông, nổi tiếng với tỷ lệ thành công cao.',
    dialogues: [
      { id: 'greet', text: 'Đan đạo đòi hỏi sự kiên nhẫn. Ngươi có đủ kiên nhẫn không?' },
      { id: 'tip', text: 'Bí quyết của ta: luôn chuẩn bị nguyên liệu dư 30%. Thất bại lần đầu là chuyện bình thường.', minRank: 2 },
      { id: 'competition', text: 'Tháng sau có Đan Hội. Ngươi có muốn tham gia không? Phần thưởng rất hậu.', minRank: 3 },
    ],
  },

  // === Huyền Cơ Các ===
  {
    id: 'elder_xuanji_array',
    name: 'Huyền Cơ Trận Lão',
    emoji: '🧙',
    sectId: 'tran_phap',
    role: 'trưởng lão trận pháp',
    minRank: 0,
    desc: 'Đại trận sư của Huyền Cơ Các, ánh mắt như nhìn thấu mọi trận pháp thiên hạ.',
    dialogues: [
      { id: 'greet', text: 'Thiên hạ vạn vật đều có quy tắc. Trận pháp là ngôn ngữ của quy tắc đó.' },
      { id: 'advice', text: 'Đừng chỉ học công thức trận pháp. Hãy hiểu ý nghĩa đằng sau từng nét vẽ.', unlockRealm: 0 },
      { id: 'secret', text: 'Ta đã nghiên cứu một trận pháp cổ đại trong ba trăm năm mà chưa phá giải được. Đây là bài toán khó nhất đời ta.', minRank: 3 },
    ],
  },
  {
    id: 'junior_xuanji_qi',
    name: 'Sư Đệ Huyền Kỳ',
    emoji: '🧑',
    sectId: 'tran_phap',
    role: 'sư đệ đồng môn',
    minRank: 0,
    desc: 'Thiên tài trận pháp trẻ tuổi, nổi tiếng với khả năng nhớ trận văn siêu phàm.',
    dialogues: [
      { id: 'greet', text: 'Sư huynh/tỷ! Ta vừa vẽ xong trận pháp thứ hai mươi, mới biết là chúng liên kết với nhau!' },
      { id: 'help', text: 'Giúp ta test trận pháp mới nhé? Chỉ cần đứng ở giữa thôi... an toàn mà, có lẽ vậy.' },
      { id: 'discovery', text: 'Ta phát hiện trong thư viện cổ có bản đồ trận pháp của tiền nhân. Nhưng chữ quá cổ không đọc được...', unlockRealm: 1 },
    ],
  },

  // === Thiết Cốt Môn ===
  {
    id: 'elder_tiecot_body',
    name: 'Thiết Cốt Môn Lão',
    emoji: '🧙',
    sectId: 'the_tu',
    role: 'trưởng lão luyện thể',
    minRank: 0,
    desc: 'Trưởng lão luyện thể của Thiết Cốt Môn, thân hình cao lớn như tháp đồng.',
    dialogues: [
      { id: 'greet', text: 'Thân thể là nền tảng của tất cả. Linh lực dù cao đến đâu, thân thể yếu là chết trước.' },
      { id: 'advice', text: 'Mỗi ngày luyện thể ít nhất một giờ. Không có ngoại lệ. Kể cả khi bị thương.', unlockRealm: 0 },
      { id: 'challenge', text: 'Ngươi muốn thử sức không? Ta đánh ngươi một chưởng — ngươi chịu được là ta nhận là Chân Truyền.', minRank: 2 },
      { id: 'praise', text: 'Thân thể ngươi đã cứng rắn hơn nhiều. Thiết Cốt Môn đã thêm một cột đồng thực sự.', minRank: 4 },
    ],
  },
  {
    id: 'junior_tiecot_ming',
    name: 'Sư Muội Thiết Minh',
    emoji: '👧',
    sectId: 'the_tu',
    role: 'sư muội đồng môn',
    minRank: 0,
    desc: 'Con gái trưởng lão, tuy nhỏ tuổi nhưng thân thể cứng rắn đáng sợ.',
    dialogues: [
      { id: 'greet', text: 'Sư huynh/tỷ! Hôm nay đã luyện chưa? Em vừa nâng lên năm nghìn cân rồi!' },
      { id: 'chat', text: 'Bên ngoài người ta cứ nghĩ Thiết Cốt Môn chỉ dùng sức. Họ nhầm rồi — chúng ta dùng ý chí.' },
      { id: 'share', text: 'Em có bí quyết hồi phục thể năng nhanh. Muốn biết không? Chỉ cần ăn nhiều hơn thôi.', unlockRealm: 0 },
    ],
  },
];

// ---- Nhiệm vụ tông môn đặc biệt ----
export const SECT_MISSIONS = [
  {
    id: 'sm_first_contribution',
    name: 'Lần Đầu Cúng Nạp',
    desc: 'Đóng góp lần đầu tiên cho tông môn.',
    requireRank: 0,
    objectives: [{ type: 'sect_contribution', qty: 1 }],
    rewards: { stone: 200, sectExp: 100 },
    oneTime: true,
  },
  {
    id: 'sm_loyal_member',
    name: 'Đệ Tử Trung Thành',
    desc: 'Đóng góp 10 lần cho tông môn.',
    requireRank: 0,
    objectives: [{ type: 'sect_contribution', qty: 10 }],
    rewards: { stone: 1000, sectExp: 500 },
    oneTime: true,
  },
  {
    id: 'sm_inner_disciple',
    name: 'Thăng Cấp Nội Môn',
    desc: 'Đạt cấp Nội Môn Đệ Tử.',
    requireRank: 1,
    objectives: [{ type: 'sect_rank', qty: 1 }],
    rewards: { stone: 2000, qi: 1000 },
    oneTime: true,
  },
  {
    id: 'sm_defend_10',
    name: 'Chiến Sĩ Tông Môn',
    desc: 'Bảo vệ tông môn 10 lần.',
    requireRank: 2,
    objectives: [{ type: 'sect_defend', qty: 10 }],
    rewards: { stone: 5000, sectExp: 2000 },
    oneTime: true,
  },
  {
    id: 'sm_elder_lecture_5',
    name: 'Học Trò Cần Mẫn',
    desc: 'Thụ giáo trưởng lão 5 lần.',
    requireRank: 1,
    objectives: [{ type: 'sect_lecture', qty: 5 }],
    rewards: { stone: 3000, ratePct: 5 },
    oneTime: true,
  },
  {
    id: 'sm_talk_all_npcs',
    name: 'Hòa Đồng Môn Nhân',
    desc: 'Nói chuyện với tất cả NPC trong tông môn.',
    requireRank: 0,
    objectives: [{ type: 'sect_npc_talk', qty: 3 }],
    rewards: { stone: 500, sectExp: 200 },
    oneTime: true,
  },
];

// ---- Sự kiện tông chiến (ngẫu nhiên) ----
export const SECT_WAR_EVENTS = [
  {
    id: 'border_skirmish',
    name: 'Xung Đột Biên Giới',
    emoji: '⚔',
    desc: 'Tông môn địch xâm phạm lãnh thổ biên giới, cần đệ tử mạnh ra đối phó.',
    minRank: 2,
    duration: 3600,
    reward: { stone: 2000, sectExp: 800, atkPct: 2 },
    penalty: { stone: -500 },
    lore: 'Tiếng chuông báo động vang lên. Đệ tử mạnh nhất tông được triệu tập.',
  },
  {
    id: 'resource_competition',
    name: 'Tranh Đoạt Linh Mạch',
    emoji: '💎',
    desc: 'Một linh mạch mới phát hiện, ba tông môn đang tranh giành quyền kiểm soát.',
    minRank: 3,
    duration: 7200,
    reward: { stone: 5000, sectExp: 1500, stoneBonus: 1 },
    penalty: { stone: -1000 },
    lore: 'Linh mạch phun linh khí lên trời — kẻ nào chiếm được sẽ hưởng lợi trăm năm.',
  },
  {
    id: 'sect_alliance_test',
    name: 'Thử Thách Đồng Minh',
    emoji: '🤝',
    desc: 'Tông môn đồng minh gửi thách đấu thân thiện để kiểm tra thực lực.',
    minRank: 1,
    duration: 1800,
    reward: { stone: 1000, sectExp: 400, expBonus: 5 },
    penalty: null,
    lore: 'Không có thù, chỉ có thực lực. Đây là cách đồng minh tin tưởng nhau.',
  },
  {
    id: 'ancient_relic_war',
    name: 'Cổ Tích Chiến',
    emoji: '🏺',
    desc: 'Một cổ tích tiền nhân xuất hiện, cả vùng tranh nhau giành lấy.',
    minRank: 4,
    duration: 14400,
    reward: { stone: 10000, sectExp: 3000, ratePct: 5 },
    penalty: { stone: -3000 },
    lore: 'Cổ tích này ngàn năm mới xuất hiện một lần. Ai giành được là đại phúc.',
  },
];