// ============================================================
// dungeon/dungeon-data.js — Địa Hạ Mê Cung
// v2 — Thêm: multiple enemies/tầng, room events ngẫu nhiên,
//      điều chỉnh minRealm về Nhân Giới (max realm 4)
// ============================================================

export const DUNGEON_NAME = 'Thiên Ma Địa Phủ';

// ---- Dungeon floors ----
// enemies: array — engine random chọn 1 để chiến
// roomEvents: sự kiện ngẫu nhiên có thể xảy ra thay vì/sau chiến đấu
export const DUNGEON_FLOORS = [

  // === Tầng 1-2: Cổng Ngoài (realm 0) ===
  {
    floor: 1,
    name: 'Cổng Âm Ti',
    emoji: '🚪',
    minRealm: 0,
    isBoss: false,
    desc: 'Cửa vào địa phủ, quỷ lính canh gác.',
    enemies: ['dungeon_ghost_1', 'dungeon_bone_soldier', 'dungeon_lost_soul'],
    roomEvents: ['find_stone_small', 'trap_minor', 'spirit_mushroom'],
    rewards: { stone: 50, exp: 100, qi: 200 },
    lore: 'Vừa bước qua cổng, hơi lạnh thấu xương. Tiếng rên rỉ vang khắp nơi.',
  },
  {
    floor: 2,
    name: 'Hành Lang Ám Phong',
    emoji: '💨',
    minRealm: 0,
    isBoss: false,
    desc: 'Ám phong mang theo linh khí độc hại.',
    enemies: ['dungeon_shadow_bat', 'dungeon_wind_wraith', 'dungeon_ghost_1'],
    roomEvents: ['dark_altar', 'find_ingredient', 'trap_minor'],
    rewards: { stone: 80, exp: 160, qi: 350 },
    lore: 'Ám phong nơi đây có thể làm loạn linh khí. Không cẩn thận sẽ tẩu hỏa nhập ma.',
  },

  // === Tầng 3-4: Âm Giới Trung Tầng (realm 1) ===
  {
    floor: 3,
    name: 'Huyết Trì',
    emoji: '🩸',
    minRealm: 1,
    isBoss: false,
    desc: 'Ao máu nuôi dưỡng quỷ vật cấp cao.',
    enemies: ['dungeon_blood_wraith', 'dungeon_crimson_demon', 'dungeon_shadow_bat'],
    roomEvents: ['blood_pool_heal', 'find_stone_medium', 'cursed_chest'],
    rewards: { stone: 120, exp: 240, qi: 500, itemId: 'dark_crystal', itemQty: 1 },
    lore: 'Huyết trì sâu không đáy. Những thứ dưới đó không ai biết chúng đã chết bao lâu.',
  },
  {
    floor: 4,
    name: 'Mê Hồn Trận',
    emoji: '🌀',
    minRealm: 1,
    isBoss: false,
    desc: 'Ảo trận giam hồn, yếu tâm thần sẽ mất trí.',
    enemies: ['dungeon_illusion_fiend', 'dungeon_mind_demon', 'dungeon_blood_wraith'],
    roomEvents: ['illusion_trial', 'find_soul_shard', 'trap_major'],
    rewards: { stone: 180, exp: 360, qi: 700, itemId: 'soul_shard', itemQty: 1 },
    lore: 'Nhìn vào mê hồn trận, ngươi thấy chính mình đang ngồi thiền dưới ánh trăng. Đừng tin vào mắt.',
  },

  // === Tầng 5: Boss 1 (realm 2) ===
  {
    floor: 5,
    name: 'Điện Diêm La',
    emoji: '👹',
    minRealm: 2,
    isBoss: true,
    desc: 'Diêm La Vương tiểu điện. Thị Vệ canh giữ.',
    enemies: ['dungeon_boss_yama_minor'],
    roomEvents: [],
    rewards: { stone: 500, exp: 1000, qi: 2000, itemId: 'yama_seal', itemQty: 1, itemId2: 'hell_core_1', itemQty2: 1 },
    lore: 'Diêm La Vương Tiểu Điện rung chuyển. Bóng người cao lớn xuất hiện — đây là thị vệ, không phải chủ chân chính.',
  },

  // === Tầng 6-7: Thâm Tầng (realm 2-3) ===
  {
    floor: 6,
    name: 'Vong Linh Hải',
    emoji: '🌊',
    minRealm: 2,
    isBoss: false,
    desc: 'Biển linh hồn người chết. Ngàn vạn oán khí.',
    enemies: ['dungeon_soul_leviathan', 'dungeon_drowned_ghost', 'dungeon_sea_wraith'],
    roomEvents: ['soul_whisper', 'find_void_essence', 'cursed_chest'],
    rewards: { stone: 300, exp: 600, qi: 1200, itemId: 'void_essence', itemQty: 1 },
    lore: 'Hàng vạn linh hồn không siêu thoát trôi dạt nơi đây. Họ chỉ muốn được giải thoát.',
  },
  {
    floor: 7,
    name: 'Băng Ngục',
    emoji: '🧊',
    minRealm: 3,
    isBoss: false,
    desc: 'Ngục băng giam những tội nhân nặng nhất.',
    enemies: ['dungeon_frost_warden', 'dungeon_ice_prisoner', 'dungeon_frozen_knight'],
    roomEvents: ['frozen_relic', 'ice_spring_heal', 'trap_freeze'],
    rewards: { stone: 450, exp: 900, qi: 1800, itemId: 'ice_prison_shard', itemQty: 1 },
    lore: 'Kẻ phạm thiên tội bị giam nơi đây muôn kiếp. Thân đông cứng nhưng thần thức vẫn còn.',
  },

  // === Tầng 8: Hỏa Tầng (realm 3) ===
  {
    floor: 8,
    name: 'Hỏa Liên Đài',
    emoji: '🔥',
    minRealm: 3,
    isBoss: false,
    desc: 'Đài lửa địa ngục, thiêu đốt nghiệp chướng.',
    enemies: ['dungeon_inferno_guardian', 'dungeon_flame_demon', 'dungeon_magma_wraith'],
    roomEvents: ['hellfire_trial', 'find_hell_flame', 'burning_chest'],
    rewards: { stone: 600, exp: 1200, qi: 2500, itemId: 'hell_flame_essence', itemQty: 1 },
    lore: 'Ngọn lửa ở đây không đốt xác — nó đốt linh hồn. Cháy mãi không tàn.',
  },

  // === Tầng 9: Thiên Ma (realm 4) ===
  {
    floor: 9,
    name: 'Thiên Ma Lâm',
    emoji: '🌑',
    minRealm: 4,
    isBoss: false,
    desc: 'Rừng ma khí dày đặc, thiên ma thức giấc.',
    enemies: ['dungeon_elder_demon', 'dungeon_shadow_lord', 'dungeon_chaos_fiend'],
    roomEvents: ['demon_pact', 'ancient_demon_relic', 'corruption_trap'],
    rewards: { stone: 800, exp: 1600, qi: 3500, itemId: 'demon_soul_crystal', itemQty: 1 },
    lore: 'Thiên ma nơi đây tu luyện ngàn năm. Ngay cả Diêm La cũng phải nể mặt.',
  },

  // === Tầng 10: Boss Cuối (realm 4) ===
  {
    floor: 10,
    name: 'Ngự Tọa Diêm Điện',
    emoji: '💀',
    minRealm: 4,
    isBoss: true,
    desc: 'Ngai vàng Diêm La Vương. Ngươi có dám?',
    enemies: ['dungeon_boss_yama_king'],
    roomEvents: [],
    rewards: { stone: 5000, exp: 10000, qi: 20000, itemId: 'yama_crown', itemQty: 1, itemId2: 'hell_core_3', itemQty2: 3 },
    lore: '"Ngươi dám đến đây — ta nể phục. Nhưng xem ngươi có qua được ta không."',
  },
];

// ---- Dungeon room events ----
// Xảy ra ngẫu nhiên (30% chance) thay thế hoặc sau combat
// type: 'reward'|'trap'|'choice'|'heal'
export const DUNGEON_ROOM_EVENTS = {
  find_stone_small: {
    id: 'find_stone_small',
    name: 'Túi Linh Thạch Bỏ Lại',
    emoji: '💎',
    type: 'reward',
    desc: 'Tìm thấy một túi linh thạch do tu sĩ trước bỏ lại trong vội vàng.',
    effect: { type: 'stone', min: 50, max: 150 },
    lore: 'Còn ấm hơi người. Chủ nhân của nó chạy đi rồi, hay là không kịp chạy?',
  },
  find_stone_medium: {
    id: 'find_stone_medium',
    name: 'Kho Linh Thạch Ẩn',
    emoji: '💰',
    type: 'reward',
    desc: 'Phát hiện kho linh thạch nhỏ ẩn trong vách đá.',
    effect: { type: 'stone', min: 200, max: 500 },
    lore: 'Ai đó đã giấu của cải ở đây với hy vọng quay lại. Có lẽ họ không bao giờ quay lại được.',
  },
  find_ingredient: {
    id: 'find_ingredient',
    name: 'Thảo Dược Địa Phủ',
    emoji: '🌿',
    type: 'reward',
    desc: 'Một loại thảo dược kỳ lạ mọc trong bóng tối địa phủ.',
    effect: { type: 'ingredient', itemId: 'dark_essence', qty: 2 },
    lore: 'Thảo dược nở hoa trong bóng tối. Kỳ lạ, nhưng lại tỏa hương thơm ngát.',
  },
  find_soul_shard: {
    id: 'find_soul_shard',
    name: 'Hồn Phách Mảnh Vỡ',
    emoji: '💠',
    type: 'reward',
    desc: 'Một mảnh hồn phách đang trôi dạt — thu lại được.',
    effect: { type: 'item', itemId: 'soul_shard', qty: 1 },
    lore: 'Mảnh hồn phách này còn có ý thức mờ nhạt. Nó cảm ơn ngươi đã thu nhận.',
  },
  find_void_essence: {
    id: 'find_void_essence',
    name: 'Hư Không Tinh Tủy Rơi Vãi',
    emoji: '🌌',
    type: 'reward',
    desc: 'Một giọt hư không tinh tủy rơi xuống từ trần — có lẽ từ chiến đấu cũ.',
    effect: { type: 'item', itemId: 'void_essence', qty: 1 },
    lore: 'Hiếm đến mức không thể mua bằng tiền. Chỉ có duyên mới nhặt được.',
  },
  find_hell_flame: {
    id: 'find_hell_flame',
    name: 'Hỏa Tinh Địa Ngục',
    emoji: '🔥',
    type: 'reward',
    desc: 'Một viên hỏa tinh địa ngục đang cháy lặng lẽ trong góc tường.',
    effect: { type: 'item', itemId: 'hell_flame_essence', qty: 1 },
    lore: 'Lửa địa ngục không cần nhiên liệu — nó tự cháy bằng nghiệp chướng.',
  },
  spirit_mushroom: {
    id: 'spirit_mushroom',
    name: 'Nấm Linh Âm Giới',
    emoji: '🍄',
    type: 'reward',
    desc: 'Nấm mọc nơi âm khí dày đặc, hấp thụ tinh hoa địa phủ qua trăm năm.',
    effect: { type: 'qi_hp', qiPct: 0.3, hpPct: 0.2 },
    lore: 'Ăn vào vừa bổ vừa có vị kỳ lạ. Không khuyến khích ăn nhiều.',
  },
  blood_pool_heal: {
    id: 'blood_pool_heal',
    name: 'Huyết Trì Tẩy Luyện',
    emoji: '🩸',
    type: 'heal',
    desc: 'Một hồ máu nhỏ phát ra khí ấm áp bất thường — ngâm vào hồi phục HP.',
    effect: { type: 'hp', pct: 0.5 },
    lore: 'Kỳ lạ. Máu địa phủ lẽ ra phải là độc, nhưng loại này lại... chữa lành?',
  },
  ice_spring_heal: {
    id: 'ice_spring_heal',
    name: 'Băng Tuyền Địa Phủ',
    emoji: '💧',
    type: 'heal',
    desc: 'Suối băng trong lành giữa ngục lạnh — uống vào hồi phục thể lực.',
    effect: { type: 'hp_stamina', hpPct: 0.4, staminaFlat: 30 },
    lore: 'Nước lạnh đến tê tay, nhưng sau khi uống cơ thể như được tắm gội từ bên trong.',
  },
  trap_minor: {
    id: 'trap_minor',
    name: 'Bẫy Quỷ Nhỏ',
    emoji: '⚠',
    type: 'trap',
    desc: 'Bẫy do quỷ vật đặt để bắt linh thú. Ngươi vô tình dẫm phải.',
    effect: { type: 'damage', hpPct: -0.1 },
    lore: 'Một cú giật mạnh rồi đau nhói. Bẫy đơn giản nhưng hiệu quả.',
  },
  trap_major: {
    id: 'trap_major',
    name: 'Ảo Trận Bẫy Hồn',
    emoji: '🌀',
    type: 'trap',
    desc: 'Ảo trận cổ đại — bị hút vào trong, mất một phần linh lực trước khi phá vỡ.',
    effect: { type: 'qi_damage', qiPct: -0.2 },
    lore: 'Tiền nhân đặt ảo trận này để bảo vệ thứ gì đó phía sau. Nhưng thứ đó đã không còn.',
  },
  trap_freeze: {
    id: 'trap_freeze',
    name: 'Băng Ngục Phong Ấn',
    emoji: '❄',
    type: 'trap',
    desc: 'Phong ấn băng cổ đại — bị đóng băng tạm thời, mất thể năng.',
    effect: { type: 'stamina', flat: -25 },
    lore: 'Băng phủ toàn thân trong tích tắc. Đau đến tê liệt, nhưng may mắn là không kéo dài.',
  },
  cursed_chest: {
    id: 'cursed_chest',
    name: 'Rương Bị Nguyền Rủa',
    emoji: '📦',
    type: 'choice',
    desc: 'Một chiếc rương cũ kỹ phát ra ánh sáng đỏ. Mở ra? (Có thể nhận thưởng hoặc bị trừng phạt)',
    choices: [
      { label: 'Mở rương', effect: { type: 'random', rewardChance: 0.5, reward: { type: 'stone', min: 300, max: 800 }, penalty: { type: 'damage', hpPct: -0.25 } } },
      { label: 'Bỏ qua', effect: null },
    ],
    lore: 'Rương phát ra hơi lạnh. Kẻ tham lam sẽ thử, kẻ thận trọng sẽ bỏ qua.',
  },
  dark_altar: {
    id: 'dark_altar',
    name: 'Tế Đàn Ám Giới',
    emoji: '🕯',
    type: 'choice',
    desc: 'Tế đàn cổ đại vẫn còn cháy. Dâng linh thạch để nhận phúc lành?',
    choices: [
      { label: 'Dâng 200 linh thạch', effect: { type: 'sacrifice_stone', cost: 200, reward: { type: 'stat', stat: 'ratePct', value: 2 } } },
      { label: 'Phá hủy tế đàn', effect: { type: 'destroy_altar', reward: { type: 'exp', amount: 500 } } },
      { label: 'Bỏ qua', effect: null },
    ],
    lore: 'Ngọn lửa đen lay động khi ngươi đến gần. Ai đã xây tế đàn này, và để làm gì?',
  },
  soul_whisper: {
    id: 'soul_whisper',
    name: 'Linh Hồn Thì Thầm',
    emoji: '👻',
    type: 'choice',
    desc: 'Một linh hồn mờ nhạt tiến đến, muốn nói điều gì đó.',
    choices: [
      { label: 'Lắng nghe', effect: { type: 'exp_burst', amount: 1000 } },
      { label: 'Xua đuổi', effect: { type: 'qi', pct: 0.2 } },
    ],
    lore: '"Ta đã từng là tu sĩ như ngươi. Hãy nghe ta nói..." Giọng như gió thổi qua kẽ đá.',
  },
  illusion_trial: {
    id: 'illusion_trial',
    name: 'Thử Thách Tâm Ma',
    emoji: '🪞',
    type: 'choice',
    desc: 'Một chiếc gương hiện ra hình ngươi — nhưng đôi mắt khác. Đối mặt với bản thân?',
    choices: [
      { label: 'Chấp nhận thử thách', effect: { type: 'stat', stat: 'ratePct', value: 3 } },
      { label: 'Phá vỡ gương', effect: { type: 'stone', min: 100, max: 300 } },
    ],
    lore: 'Hình trong gương cười lạnh: "Ngươi có đủ can đảm nhìn thẳng vào mình không?"',
  },
  ancient_demon_relic: {
    id: 'ancient_demon_relic',
    name: 'Cổ Vật Thiên Ma',
    emoji: '🗿',
    type: 'reward',
    desc: 'Cổ vật của thiên ma cổ đại còn sót lại — ngấm đầy ma khí tinh thuần.',
    effect: { type: 'item', itemId: 'demon_soul_crystal', qty: 1 },
    lore: 'Thiên ma để lại vật này không phải vô tình. Nhưng duyên cớ đã mất theo thời gian.',
  },
  hellfire_trial: {
    id: 'hellfire_trial',
    name: 'Nghiệp Hỏa Thử Tâm',
    emoji: '🔥',
    type: 'choice',
    desc: 'Ngọn lửa nghiệp chướng mời gọi — đi qua sẽ tẩy luyện tâm hồn, hoặc bị đốt cháy.',
    choices: [
      { label: 'Đi qua lửa', effect: { type: 'random', rewardChance: 0.65, reward: { type: 'stat', stat: 'defPct', value: 5 }, penalty: { type: 'damage', hpPct: -0.3 } } },
      { label: 'Tránh lửa', effect: null },
    ],
    lore: 'Những ai vượt qua nghiệp hỏa mà không cháy được gọi là người đã giải nghiệp.',
  },
  demon_pact: {
    id: 'demon_pact',
    name: 'Khế Ước Thiên Ma',
    emoji: '📜',
    type: 'choice',
    desc: 'Một thiên ma cấp thấp đề nghị giao dịch: sức mạnh đổi lấy thọ mệnh.',
    choices: [
      { label: 'Ký khế ước (-5 năm thọ, +15% ATK)', effect: { type: 'pact', lifespanCost: 5, atkPctGain: 15 } },
      { label: 'Từ chối', effect: { type: 'exp_burst', amount: 800 } },
    ],
    lore: 'Ma quỷ không bao giờ cho không. Nhưng đôi khi giá cả lại... hợp lý.',
  },
  corruption_trap: {
    id: 'corruption_trap',
    name: 'Ma Khí Ô Nhiễm',
    emoji: '☣',
    type: 'trap',
    desc: 'Vùng ma khí đặc biệt — ngươi bị ngấm vào trước khi kịp tránh.',
    effect: { type: 'damage', hpPct: -0.15 },
    lore: 'Ma khí thiên ma khác hẳn yêu khí bình thường — nó ăn mòn từng tế bào linh thể.',
  },
  burning_chest: {
    id: 'burning_chest',
    name: 'Rương Lửa Địa Ngục',
    emoji: '🔥',
    type: 'choice',
    desc: 'Rương bao phủ bởi lửa địa ngục — chạm vào thì bỏng, nhưng bên trong có thể có gì đó quý.',
    choices: [
      { label: 'Chịu đau mở rương (-10% HP, nhận thưởng)', effect: { type: 'fire_chest', hpCost: 0.10, reward: { type: 'item', itemId: 'hell_flame_essence', qty: 2 } } },
      { label: 'Bỏ qua', effect: null },
    ],
    lore: 'Lửa địa ngục bảo vệ kho báu tốt hơn bất kỳ khóa nào.',
  },
  frozen_relic: {
    id: 'frozen_relic',
    name: 'Di Vật Đông Băng',
    emoji: '🧊',
    type: 'reward',
    desc: 'Một di vật bị đông băng ngàn năm — tan ra và trao linh khí tích tụ cho ngươi.',
    effect: { type: 'qi', pct: 0.6 },
    lore: 'Linh khí băng ngàn năm ngưng đọng trong di vật. Khi tan, nó tuôn vào cơ thể ngươi như thác lũ.',
  },
};

// ---- Dungeon enemies ----
export const DUNGEON_ENEMIES = [
  // Tầng 1-2
  {
    id: 'dungeon_ghost_1',
    name: 'Ám Quỷ Canh Cửa', emoji: '👻',
    hpBase: 200, atkBase: 15, defBase: 5, spdBase: 10,
    expReward: 80, stoneReward: [30, 60],
    skills: ['ghost_touch', 'wail'],
    lore: 'Quỷ binh canh gác cổng địa phủ, yếu nhưng số lượng vô hạn.',
  },
  {
    id: 'dungeon_bone_soldier',
    name: 'Bạch Cốt Binh', emoji: '💀',
    hpBase: 280, atkBase: 20, defBase: 15, spdBase: 7,
    expReward: 100, stoneReward: [40, 80],
    skills: ['heavy_blow', 'stone_skin'],
    lore: 'Tàn cốt của binh sĩ xưa, bị trói buộc bởi oan hồn phải canh giữ địa phủ đời đời.',
  },
  {
    id: 'dungeon_lost_soul',
    name: 'Oan Hồn Lạc Lối', emoji: '🌫',
    hpBase: 150, atkBase: 18, defBase: 3, spdBase: 18,
    expReward: 90, stoneReward: [35, 70],
    skills: ['ghost_touch', 'curse'],
    lore: 'Người chết không siêu thoát được, cứ vật vờ lang thang trong địa phủ.',
  },
  {
    id: 'dungeon_shadow_bat',
    name: 'Hư Ảnh Huyết Bức', emoji: '🦇',
    hpBase: 350, atkBase: 25, defBase: 8, spdBase: 20,
    expReward: 140, stoneReward: [50, 100],
    skills: ['shadow_bite', 'darkness_veil'],
    lore: 'Dơi địa phủ bay trong bóng tối, hút linh khí của người tu luyện.',
  },
  {
    id: 'dungeon_wind_wraith',
    name: 'Ám Phong Quỷ', emoji: '💨',
    hpBase: 300, atkBase: 30, defBase: 5, spdBase: 25,
    expReward: 130, stoneReward: [50, 95],
    skills: ['wail', 'shadow_bite'],
    lore: 'Hình thành từ ám phong địa phủ ngưng tụ, tấn công nhanh như gió.',
  },
  // Tầng 3-4
  {
    id: 'dungeon_blood_wraith',
    name: 'Huyết Oan Hồn', emoji: '🩸',
    hpBase: 600, atkBase: 50, defBase: 20, spdBase: 15,
    expReward: 250, stoneReward: [100, 200],
    skills: ['blood_drain', 'curse'],
    lore: 'Kẻ chết trong uất hận, máu không khô, oán không tiêu.',
  },
  {
    id: 'dungeon_crimson_demon',
    name: 'Đỏ Huyết Ma', emoji: '🔴',
    hpBase: 700, atkBase: 55, defBase: 25, spdBase: 12,
    expReward: 280, stoneReward: [110, 220],
    skills: ['blood_drain', 'heavy_blow'],
    lore: 'Đỉnh cao của quỷ vật huyết hệ, toàn thân đỏ thẫm như ngâm trong máu.',
  },
  {
    id: 'dungeon_illusion_fiend',
    name: 'Mê Ảnh Ma', emoji: '🌀',
    hpBase: 900, atkBase: 70, defBase: 30, spdBase: 25,
    expReward: 380, stoneReward: [150, 300],
    skills: ['illusion_strike', 'mind_break'],
    lore: 'Quỷ vật chuyên tạo ảo ảnh, khiến đối thủ không phân biệt thật giả.',
  },
  {
    id: 'dungeon_mind_demon',
    name: 'Tâm Ma Quỷ', emoji: '🧠',
    hpBase: 800, atkBase: 65, defBase: 20, spdBase: 22,
    expReward: 350, stoneReward: [140, 280],
    skills: ['mind_break', 'curse'],
    lore: 'Tâm ma chuyên tấn công tinh thần, khiến ký ức và suy nghĩ loạn xạ.',
  },
  // Boss tầng 5
  {
    id: 'dungeon_boss_yama_minor',
    name: 'Thị Vệ Diêm La', emoji: '👹',
    hpBase: 5000, atkBase: 200, defBase: 100, spdBase: 18,
    expReward: 2000, stoneReward: [800, 1500],
    skills: ['yama_strike', 'death_aura', 'judgment'],
    lore: 'Diêm La Vương có mười tám thị vệ thần lực vô biên. Đây chỉ là một trong số đó.',
    isBoss: true,
  },
  // Tầng 6-8
  {
    id: 'dungeon_soul_leviathan',
    name: 'Vong Linh Hải Thú', emoji: '🌊',
    hpBase: 8000, atkBase: 350, defBase: 150, spdBase: 12,
    expReward: 3200, stoneReward: [1200, 2400],
    skills: ['soul_crush', 'tidal_wave', 'devour'],
    lore: 'Sinh từ vạn vạn linh hồn tích tụ, không có ý thức — chỉ có đói.',
  },
  {
    id: 'dungeon_drowned_ghost',
    name: 'Vong Linh Chết Chìm', emoji: '🌊',
    hpBase: 6000, atkBase: 300, defBase: 120, spdBase: 10,
    expReward: 2500, stoneReward: [1000, 2000],
    skills: ['tidal_wave', 'curse'],
    lore: 'Tu sĩ chết đuối trong vong linh hải, linh hồn bị giữ lại biến thành quái vật.',
  },
  {
    id: 'dungeon_sea_wraith',
    name: 'Hải Oan Ma', emoji: '💧',
    hpBase: 7000, atkBase: 320, defBase: 130, spdBase: 15,
    expReward: 2800, stoneReward: [1100, 2200],
    skills: ['blood_drain', 'soul_crush'],
    lore: 'Hình thành từ oán khí của biển vong linh, chuyên hút linh hồn người sống.',
  },
  {
    id: 'dungeon_frost_warden',
    name: 'Băng Ngục Cai Ngục', emoji: '🧊',
    hpBase: 12000, atkBase: 500, defBase: 250, spdBase: 8,
    expReward: 5000, stoneReward: [2000, 4000],
    skills: ['frost_prison', 'ice_spear', 'absolute_zero'],
    lore: 'Canh giữ băng ngục ngàn năm, bản thân cũng đã đông cứng một nửa.',
  },
  {
    id: 'dungeon_ice_prisoner',
    name: 'Tử Tù Băng Ngục', emoji: '🧊',
    hpBase: 9000, atkBase: 420, defBase: 200, spdBase: 6,
    expReward: 3800, stoneReward: [1600, 3200],
    skills: ['frost_prison', 'heavy_blow'],
    lore: 'Tử tù bị giam ngàn năm trong băng, hận thù đông đặc thành sức chiến đấu.',
  },
  {
    id: 'dungeon_frozen_knight',
    name: 'Băng Hà Chiến Kỵ', emoji: '⚔',
    hpBase: 10000, atkBase: 460, defBase: 230, spdBase: 10,
    expReward: 4200, stoneReward: [1800, 3500],
    skills: ['ice_spear', 'stone_skin'],
    lore: 'Kỵ sĩ bị đóng băng trong cuộc chiến cổ đại, linh hồn vẫn tiếp tục chiến đấu.',
  },
  {
    id: 'dungeon_inferno_guardian',
    name: 'Hỏa Liên Đài Thủ Giả', emoji: '🔥',
    hpBase: 18000, atkBase: 700, defBase: 350, spdBase: 20,
    expReward: 7500, stoneReward: [3000, 6000],
    skills: ['inferno_blast', 'flame_aura', 'hellfire'],
    lore: 'Đốt mình trong lửa địa ngục suốt ngàn năm, giờ không còn biết đau là gì.',
  },
  {
    id: 'dungeon_flame_demon',
    name: 'Nghiệp Hỏa Ma', emoji: '🔥',
    hpBase: 14000, atkBase: 600, defBase: 280, spdBase: 22,
    expReward: 6000, stoneReward: [2400, 4800],
    skills: ['inferno_blast', 'hellfire'],
    lore: 'Sinh từ nghiệp hỏa tích tụ của vô số tội nhân, toàn thân bốc lửa.',
  },
  {
    id: 'dungeon_magma_wraith',
    name: 'Nham Tương Quỷ', emoji: '🌋',
    hpBase: 16000, atkBase: 650, defBase: 320, spdBase: 15,
    expReward: 6800, stoneReward: [2700, 5500],
    skills: ['flame_aura', 'inferno_blast'],
    lore: 'Hình thành từ dung nham địa phủ, cứng như đá và nóng như lò nung.',
  },
  // Tầng 9
  {
    id: 'dungeon_elder_demon',
    name: 'Thiên Ma Trưởng Lão', emoji: '🌑',
    hpBase: 28000, atkBase: 1000, defBase: 500, spdBase: 30,
    expReward: 12000, stoneReward: [5000, 10000],
    skills: ['demon_domain', 'void_slash', 'corruption'],
    lore: 'Tu luyện ba ngàn năm trong thiên ma lâm. Ngay cả Diêm La cũng phải nể mặt.',
  },
  {
    id: 'dungeon_shadow_lord',
    name: 'Ám Ảnh Chúa', emoji: '🌑',
    hpBase: 22000, atkBase: 900, defBase: 420, spdBase: 35,
    expReward: 10000, stoneReward: [4200, 8500],
    skills: ['void_slash', 'demon_domain'],
    lore: 'Chúa tể của bóng tối thiên ma lâm, có thể hóa thành bóng tối và tàng hình hoàn toàn.',
  },
  {
    id: 'dungeon_chaos_fiend',
    name: 'Hỗn Độn Quỷ Vật', emoji: '🌀',
    hpBase: 25000, atkBase: 950, defBase: 450, spdBase: 28,
    expReward: 11000, stoneReward: [4500, 9000],
    skills: ['corruption', 'void_slash'],
    lore: 'Quỷ vật tổng hợp từ tất cả loại ma khí — không có nguyên tố cố định, công phá mọi phòng thủ.',
  },
  // Boss tầng 10
  {
    id: 'dungeon_boss_yama_king',
    name: 'Diêm La Đại Vương', emoji: '💀',
    hpBase: 100000, atkBase: 3000, defBase: 1500, spdBase: 35,
    expReward: 50000, stoneReward: [20000, 40000],
    skills: ['death_decree', 'soul_reap', 'yama_domain', 'resurrection'],
    lore: 'Chủ tể của địa phủ. Ba ngàn năm không ai đặt chân vào đây mà sống sót.',
    isBoss: true,
  },
];

// ---- Dungeon enemy skills ----
export const DUNGEON_ENEMY_SKILLS = {
  ghost_touch:      { name: 'Âm Ma Xúc',          dmgMult: 1.2, chance: 0.6, effect: null },
  wail:             { name: 'Oan Hồn Bi Hao',      dmgMult: 0.8, chance: 0.3, effect: { type: 'stun', turns: 1 } },
  shadow_bite:      { name: 'Ám Ảnh Cắn',          dmgMult: 1.4, chance: 0.5, effect: { type: 'burn', dmgPerTurn: 20, turns: 2 } },
  darkness_veil:    { name: 'Màn Đêm Phủ',         dmgMult: 0.5, chance: 0.6, effect: null },
  blood_drain:      { name: 'Hút Huyết',            dmgMult: 1.5, chance: 0.7, effect: { type: 'lifesteal', pct: 0.3 } },
  curse:            { name: 'Lời Nguyền',           dmgMult: 1.0, chance: 0.4, effect: { type: 'stun', turns: 2 } },
  illusion_strike:  { name: 'Ảo Kiếm Vạn Biến',    dmgMult: 1.8, chance: 0.6, effect: null },
  mind_break:       { name: 'Phá Tâm Ma',           dmgMult: 1.2, chance: 0.6, effect: { type: 'stun', turns: 2 } },
  heavy_blow:       { name: 'Đòn Trọng',            dmgMult: 1.8, chance: 0.3, effect: { type: 'stun', turns: 1 } },
  stone_skin:       { name: 'Da Đá',                dmgMult: 0,   chance: 0.3, effect: { type: 'buff_def', pct: 30 } },
  yama_strike:      { name: 'Diêm La Nhất Kích',    dmgMult: 2.0, chance: 0.5, effect: null },
  death_aura:       { name: 'Tử Khí Quang Hoàn',   dmgMult: 1.2, chance: 0.8, effect: { type: 'burn', dmgPerTurn: 60, turns: 3 } },
  judgment:         { name: 'Phán Quan Xét Xử',    dmgMult: 2.5, chance: 0.5, effect: { type: 'stun', turns: 1 } },
  soul_crush:       { name: 'Hồn Phách Nghiền',     dmgMult: 2.2, chance: 0.5, effect: { type: 'stun', turns: 2 } },
  tidal_wave:       { name: 'Linh Hồn Cuồng Triều', dmgMult: 1.6, chance: 0.9, effect: { type: 'burn', dmgPerTurn: 80, turns: 2 } },
  devour:           { name: 'Thôn Thực',            dmgMult: 3.0, chance: 0.4, effect: null },
  frost_prison:     { name: 'Băng Ngục',            dmgMult: 1.5, chance: 0.6, effect: { type: 'stun', turns: 3 } },
  ice_spear:        { name: 'Băng Thương',          dmgMult: 2.0, chance: 0.7, effect: { type: 'burn', dmgPerTurn: 50, turns: 3 } },
  absolute_zero:    { name: 'Tuyệt Đối Không Độ',  dmgMult: 4.0, chance: 0.9, effect: { type: 'stun', turns: 2 } },
  inferno_blast:    { name: 'Địa Ngục Thiêu',       dmgMult: 2.5, chance: 0.9, effect: { type: 'burn', dmgPerTurn: 100, turns: 3 } },
  flame_aura:       { name: 'Hỏa Liên Quang Hoàn', dmgMult: 1.0, chance: 1.0, effect: { type: 'burn', dmgPerTurn: 120, turns: 4 } },
  hellfire:         { name: 'Nghiệp Hỏa',           dmgMult: 5.0, chance: 0.3, effect: null },
  demon_domain:     { name: 'Thiên Ma Lĩnh Vực',    dmgMult: 2.0, chance: 0.8, effect: { type: 'stun', turns: 1 } },
  void_slash:       { name: 'Hư Không Nhất Đao',   dmgMult: 3.5, chance: 0.4, effect: null },
  corruption:       { name: 'Ma Khí Ô Nhiễm',       dmgMult: 1.8, chance: 0.9, effect: { type: 'burn', dmgPerTurn: 200, turns: 3 } },
  death_decree:     { name: 'Tử Mệnh Chiếu Thư',   dmgMult: 3.0, chance: 0.7, effect: { type: 'stun', turns: 2 } },
  soul_reap:        { name: 'Thu Linh',             dmgMult: 4.0, chance: 1.0, effect: { type: 'burn', dmgPerTurn: 500, turns: 2 } },
  yama_domain:      { name: 'Diêm La Địa Phủ',      dmgMult: 2.5, chance: 0.8, effect: { type: 'stun', turns: 3 } },
  resurrection:     { name: 'Hồi Sinh',             dmgMult: 0,   chance: 0.6, effect: { type: 'self_heal', pct: 0.3 } },
};

// ---- Dungeon items ----
export const DUNGEON_ITEMS = {
  dark_crystal:       { name: 'Ám Tinh Thạch',        emoji: '🔮', desc: 'Tinh thạch từ địa phủ, chứa âm khí thuần túy.' },
  soul_shard:         { name: 'Hồn Phách Mảnh',        emoji: '💠', desc: 'Mảnh linh hồn của mê ảnh ma, có thể dùng để luyện đan.' },
  yama_seal:          { name: 'Diêm La Phong Ấn',       emoji: '⚖', desc: 'Phong ấn Diêm La, chứng minh đã qua tầng 5.' },
  hell_core_1:        { name: 'Địa Phủ Nguyên Anh (Sơ)',  emoji: '💀', desc: 'Nguyên anh của quỷ vật địa phủ cấp thấp.' },
  hell_core_3:        { name: 'Địa Phủ Nguyên Anh (Thượng)', emoji: '💀', desc: 'Nguyên anh tinh thuần từ cường giả địa phủ.' },
  void_essence:       { name: 'Hư Không Tinh Tủy',      emoji: '🌌', desc: 'Tinh tủy từ vong linh hải, quý hiếm vô cùng.' },
  ice_prison_shard:   { name: 'Băng Ngục Mảnh',          emoji: '🧊', desc: 'Mảnh vỡ từ băng ngục ngàn năm không tan.' },
  hell_flame_essence: { name: 'Địa Ngục Hỏa Tinh',       emoji: '🔥', desc: 'Tinh hoa của ngọn lửa địa ngục, đốt linh hồn.' },
  demon_soul_crystal: { name: 'Thiên Ma Hồn Tinh',        emoji: '🌑', desc: 'Tinh thể hồn phách của thiên ma trưởng lão.' },
  dark_essence:       { name: 'Ám Tinh Tủy',              emoji: '🌑', desc: 'Tinh tủy từ bóng tối địa phủ, nguyên liệu đan dược.' },
  yama_crown:         { name: 'Diêm La Vương Miện',       emoji: '👑', desc: 'Vương miện của Diêm La. Ngươi thực sự đã làm được.' },
};