// ============================================================
// quest/quest-data.js — Quest definitions
// v2 — Thêm: 15 side quest, 12 daily, 10 bounty, 5 sect quest
// ============================================================

export const QUESTS = [

  // ============================================================
  // STORY QUESTS — chain chính, theo thứ tự
  // (Nhân Giới: sq_01 đến sq_10, Linh/Tiên Giới: sq_11+ cho tương lai)
  // ============================================================
  {
    id: 'sq_00_meet_elder',
    name: 'Gặp Gỡ Trưởng Lão',
    type: 'story', chain: 'main', order: 0,
    desc: 'Đến gặp Trưởng Lão tại làng để nghe lời chỉ dẫn ban đầu.',
    unlockRealm: 0,
    autoAccept: true, // tự nhận khi bắt đầu game
    objectives: [{ key: 'talk_npc', target: 'elder', label: 'Nói chuyện Trưởng Lão', required: 1 }],
    rewards: { stone: 8, exp: 50, item: 'qi_pill_basic', unlockQuest: 'sq_01_first_kill' },
    lore: '\"Ngươi đã đến rồi. Ta chờ đã lâu. Trước tiên, hãy để ta nói cho ngươi nghe về con đường phía trước.\"',
    npcHint: '👴 Trưởng Lão đang đứng ở trung tâm làng. Hãy đến nói chuyện để bắt đầu hành trình.',
  },
  {
    id: 'sq_01_first_kill',
    name: 'Bước Đầu Trên Đường Tu',
    type: 'story', chain: 'main', order: 1,
    desc: 'Trưởng Lão dặn: Diệt con yêu thú đầu tiên ở khu vực ngoại ô để rèn giũa bản thân.',
    unlockRealm: 0,
    objectives: [{ key: 'kill', label: 'Diệt yêu thú', required: 1 }],
    rewards: { stone: 12, exp: 100, unlockQuest: 'sq_02_gather_herb' },
    lore: 'Mỗi cao nhân đều có lần đầu tiên — đây là bước đầu của ngươi.',
    npcHint: '🌲 Vào 🗺 Bản Đồ → Rừng Ven Thôn → Săn Thú để tìm yêu thú đầu tiên.',
  },
  {
    id: 'sq_02_gather_herb',
    name: 'Linh Thảo Tiên Phương',
    type: 'story', chain: 'main', order: 2,
    desc: 'Thu thập linh thảo để luyện đan cơ bản.',
    unlockRealm: 0,
    objectives: [{ key: 'gather', label: 'Thu thập nguyên liệu', required: 3 }],
    rewards: { stone: 20, exp: 150, recipe: 'healing_pill', unlockQuest: 'sq_03_first_pill' },
    lore: 'Đan sư nói: không có linh thảo, không có đan dược.',
  },
  {
    id: 'sq_03_first_pill',
    name: 'Sơ Nhập Đan Đạo',
    type: 'story', chain: 'main', order: 3,
    desc: 'Luyện thành viên đan đầu tiên.',
    unlockRealm: 0,
    objectives: [{ key: 'alchemy', label: 'Luyện đan thành công', required: 1 }],
    rewards: { stone: 24, exp: 200, unlockQuest: 'sq_04_breakthrough' },
    lore: 'Khi lửa đan bùng cháy lần đầu, ngươi biết đây là con đường của mình.',
  },
  {
    id: 'sq_04_breakthrough',
    name: 'Vượt Cảnh Giới',
    type: 'story', chain: 'main', order: 4,
    desc: 'Đột phá lần đầu tiên.',
    unlockRealm: 0,
    objectives: [{ key: 'breakthrough', label: 'Đột phá cảnh giới', required: 1 }],
    rewards: { stone: 40, exp: 300, recipe: 'cultivate_pill', unlockQuest: 'sq_05_truc_co' },
    lore: 'Mỗi lần đột phá là một lần chết đi sống lại.',
  },
  {
    id: 'sq_05_truc_co',
    name: 'Trúc Cơ Thành Tựu',
    type: 'story', chain: 'main', order: 5,
    desc: 'Đạt đến cảnh giới Trúc Cơ.',
    unlockRealm: 0,
    objectives: [{ key: 'reach_realm', target: 1, label: 'Đạt Trúc Cơ', required: 1 }],
    rewards: { stone: 100, exp: 800, recipe: 'strength_pill', unlockQuest: 'sq_06_defeat_general' },
    lore: 'Trúc Cơ viên mãn — ngươi chính thức trở thành tu sĩ thực thụ.',
  },
  {
    id: 'sq_06_defeat_general',
    name: 'Thảo Phạt Yêu Tướng',
    type: 'story', chain: 'main', order: 6,
    desc: 'Tiêu diệt Yêu Tướng Hắc Giáp — mối họa lớn nhất vùng này.',
    unlockRealm: 2,
    objectives: [{ key: 'kill_specific', target: 'demon_general', label: 'Diệt Yêu Tướng', required: 1 }],
    rewards: { stone: 150, exp: 2000, recipe: 'breakthrough_aid', unlockQuest: 'sq_07_nguyen_anh' },
    lore: 'Yêu Tướng Hắc Giáp đã tàn sát ngàn người tu. Đã đến lúc kết thúc.',
  },
  {
    id: 'sq_07_nguyen_anh',
    name: 'Nguyên Anh Xuất Thế',
    type: 'story', chain: 'main', order: 7,
    desc: 'Đột phá đến cảnh giới Nguyên Anh.',
    unlockRealm: 2,
    objectives: [{ key: 'reach_realm', target: 3, label: 'Đạt Nguyên Anh', required: 1 }],
    rewards: { stone: 300, exp: 5000, unlockQuest: 'sq_08_blood_bat' },
    lore: 'Nguyên Anh cất tiếng khóc chào đời — linh hồn và thể xác hợp nhất. Thiên địa rung chuyển.',
  },
  {
    id: 'sq_08_blood_bat',
    name: 'Huyết Dực Ô Vân',
    type: 'story', chain: 'main', order: 8,
    desc: 'Đàn Huyết Dực Ma Thú đang tàn phá vùng linh địa, hãy tiêu diệt 3 con.',
    unlockRealm: 3,
    objectives: [{ key: 'kill_specific', target: 'blood_bat', label: 'Diệt Huyết Dực Ma Thú', required: 3 }],
    rewards: { stone: 300, exp: 7000, unlockQuest: 'sq_09_hoa_than' },
    lore: 'Những đàn ma thú uống máu đe dọa cả khu linh địa.',
  },
  {
    id: 'sq_09_hoa_than',
    name: 'Hóa Thần Chi Cảnh',
    type: 'story', chain: 'main', order: 9,
    desc: 'Đột phá Hóa Thần — đỉnh cao của Nhân Giới.',
    unlockRealm: 3,
    objectives: [{ key: 'reach_realm', target: 4, label: 'Đạt Hóa Thần', required: 1 }],
    rewards: { stone: 500, exp: 12000, unlockQuest: 'sq_10_earth_dragon' },
    lore: 'Hóa Thần — khi tinh thần hóa thành thần, vũ trụ thu vào trong tâm.',
  },
  {
    id: 'sq_10_earth_dragon',
    name: 'Phục Long Chiến',
    type: 'story', chain: 'main', order: 10,
    desc: 'Địa Long Cổ Thần thức giấc, đánh bại nó để thu phục linh địa — hoàn thành hành trình Nhân Giới.',
    unlockRealm: 4,
    objectives: [{ key: 'kill_specific', target: 'earth_dragon', label: 'Đánh bại Địa Long', required: 1 }],
    rewards: { stone: 800, exp: 20000 },
    lore: 'Ngàn năm ngủ vùi trong lòng đất, Địa Long thức dậy trong cơn thịnh nộ. Đây là thử thách cuối cùng của Nhân Giới.',
  },
  // Story cho Linh Giới+ (reserve, chưa triển khai)
  {
    id: 'sq_11_luyen_hu',
    name: 'Luyện Hư Đại Đạo',
    type: 'story', chain: 'main', order: 11,
    desc: '(Linh Giới) Đạt cảnh giới Luyện Hư.',
    unlockRealm: 5,
    objectives: [{ key: 'reach_realm', target: 5, label: 'Đạt Luyện Hư', required: 1 }],
    rewards: { stone: 1200, exp: 30000, unlockQuest: 'sq_12_void_demon' },
    lore: 'Luyện Hư — luyện cái hư không vô tướng thành đại đạo.',
  },
  {
    id: 'sq_12_void_demon',
    name: 'Ma Vương Hư Không',
    type: 'story', chain: 'main', order: 12,
    desc: '(Linh Giới) Hư Không Ma Vương mở cửa hư không, hãy ngăn chặn.',
    unlockRealm: 5,
    objectives: [{ key: 'kill_specific', target: 'void_demon', label: 'Đánh bại Hư Không Ma Vương', required: 1 }],
    rewards: { stone: 2000, exp: 50000 },
    lore: 'Từ khe nứt hư không, Ma Vương bước ra với sức mạnh nuốt trời vào đất.',
  },

  // ============================================================
  // SIDE QUESTS — không bắt buộc, phần thưởng tốt
  // ============================================================

  // --- Chiến đấu ---
  {
    id: 'side_hunter_01',
    name: 'Liệp Yêu Sơ Học',
    type: 'side', category: 'combat',
    desc: 'Diệt 10 yêu thú.',
    unlockRealm: 0,
    objectives: [{ key: 'kill', label: 'Diệt yêu thú', required: 10 }],
    rewards: { stone: 30, exp: 200 },
    repeatable: false,
    lore: 'Tu sĩ không rèn kiếm ở trường đấu — họ rèn trong máu và lửa thực chiến.',
  },
  {
    id: 'side_hunter_02',
    name: 'Bách Yêu Thách Đấu',
    type: 'side', category: 'combat',
    desc: 'Diệt 100 yêu thú.',
    unlockRealm: 0,
    prereq: 'side_hunter_01',
    objectives: [{ key: 'kill', label: 'Diệt yêu thú', required: 100 }],
    rewards: { stone: 100, exp: 800, recipe: 'defense_pill' },
    repeatable: false,
    lore: 'Trăm trận thành thần. Mỗi trận chiến là một bài học.',
  },
  {
    id: 'side_hunter_03',
    name: 'Vạn Yêu Đồ Sát',
    type: 'side', category: 'combat',
    desc: 'Diệt 500 yêu thú — danh hiệu Đồ Yêu Giả.',
    unlockRealm: 1,
    prereq: 'side_hunter_02',
    objectives: [{ key: 'kill', label: 'Diệt yêu thú', required: 500 }],
    rewards: { stone: 300, exp: 3000, recipe: 'strength_pill' },
    repeatable: false,
    lore: 'Ngươi đã trở thành ác mộng của yêu tộc.',
  },
  {
    id: 'side_wolf_slayer',
    name: 'Trừ Sói Linh Sơn',
    type: 'side', category: 'combat',
    desc: 'Tiêu diệt 15 Yêu Sói Đen đang quấy phá Linh Sơn.',
    unlockRealm: 0,
    objectives: [{ key: 'kill_specific', target: 'demon_wolf', label: 'Diệt Yêu Sói Đen', required: 15 }],
    rewards: { stone: 60, exp: 400 },
    repeatable: false,
    lore: 'Bầy sói yêu dạo gần làng, tiều phu không dám vào rừng. Hãy giải quyết chúng.',
  },
  {
    id: 'side_ice_serpent',
    name: 'Băng Xà Hiểm Địa',
    type: 'side', category: 'combat',
    desc: 'Tiêu diệt 5 Băng Hàn Xà kiểm soát đường lên băng sơn.',
    unlockRealm: 1,
    objectives: [{ key: 'kill_specific', target: 'ice_serpent', label: 'Diệt Băng Hàn Xà', required: 5 }],
    rewards: { stone: 120, exp: 1200, recipe: 'han_bing_dan' },
    repeatable: false,
    lore: 'Đường lên băng sơn bị Băng Hàn Xà chiếm. Ai muốn qua phải trả bằng máu.',
  },
  {
    id: 'side_phantom_fox',
    name: 'Ảo Ảnh Hồ Truy Sát',
    type: 'side', category: 'combat',
    desc: 'Đánh bại 3 Ảo Ảnh Cửu Vĩ Hồ đang mê hoặc tu sĩ.',
    unlockRealm: 3,
    objectives: [{ key: 'kill_specific', target: 'phantom_fox', label: 'Diệt Ảo Ảnh Cửu Vĩ Hồ', required: 3 }],
    rewards: { stone: 400, exp: 6000 },
    repeatable: false,
    lore: 'Cửu Vĩ Hồ hóa hình thiếu nữ mê hoặc tu sĩ, nhiều người mất cả công lực.',
  },

  // --- Luyện đan ---
  {
    id: 'side_alchemy_01',
    name: 'Đan Sư Sơ Cấp',
    type: 'side', category: 'alchemy',
    desc: 'Luyện đan thành công 5 lần.',
    unlockRealm: 0,
    objectives: [{ key: 'alchemy', label: 'Luyện đan thành công', required: 5 }],
    rewards: { stone: 40, exp: 300 },
    repeatable: false,
    lore: 'Năm lần thành công — đủ để gọi là có duyên với đan đạo.',
  },
  {
    id: 'side_alchemy_02',
    name: 'Đan Sư Trung Cấp',
    type: 'side', category: 'alchemy',
    desc: 'Luyện đan thành công 30 lần.',
    unlockRealm: 1,
    prereq: 'side_alchemy_01',
    objectives: [{ key: 'alchemy', label: 'Luyện đan thành công', required: 30 }],
    rewards: { stone: 120, exp: 1000, recipe: 'dan_dao_dan' },
    repeatable: false,
    lore: 'Ba mươi lần luyện — lò đan quen hơi tay ngươi rồi.',
  },
  {
    id: 'side_alchemy_03',
    name: 'Đại Đan Sư',
    type: 'side', category: 'alchemy',
    desc: 'Luyện đan thành công 100 lần — danh hiệu Đại Đan Sư.',
    unlockRealm: 2,
    prereq: 'side_alchemy_02',
    objectives: [{ key: 'alchemy', label: 'Luyện đan thành công', required: 100 }],
    rewards: { stone: 300, exp: 5000, recipe: 'zhen_qi_dan' },
    repeatable: false,
    lore: 'Trăm lần luyện đan — tên ngươi bắt đầu được nhắc đến trong giới đan sư.',
  },

  // --- Thu thảo & Khám phá ---
  {
    id: 'side_explore_01',
    name: 'Khám Phá Bốn Phương',
    type: 'side', category: 'explore',
    desc: 'Thu thập nguyên liệu 20 lần.',
    unlockRealm: 0,
    objectives: [{ key: 'gather', label: 'Thu thập', required: 20 }],
    rewards: { stone: 60, exp: 400 },
    repeatable: false,
    lore: 'Kẻ không dám rời tông môn sẽ không bao giờ tìm thấy cơ duyên thực sự.',
  },
  {
    id: 'side_gather_lotus',
    name: 'Sen Linh Ngàn Hoa',
    type: 'side', category: 'explore',
    desc: 'Thu thập 10 Bạch Ngọc Liên từ các hồ sen linh.',
    unlockRealm: 0,
    objectives: [{ key: 'gather_specific', target: 'jade_lotus', label: 'Thu Bạch Ngọc Liên', required: 10 }],
    rewards: { stone: 80, exp: 500, recipe: 'shou_yuan_dan_1' },
    repeatable: false,
    lore: 'Hoa sen linh nở trong im lặng, ai biết nhẫn nại mới tìm thấy đủ.',
  },

  // --- Đột phá ---
  {
    id: 'side_break_05',
    name: 'Ngũ Đột Kỳ Nhân',
    type: 'side', category: 'cultivate',
    desc: 'Đột phá 5 lần.',
    unlockRealm: 0,
    objectives: [{ key: 'breakthrough', label: 'Đột phá', required: 5 }],
    rewards: { stone: 80, exp: 600 },
    repeatable: false,
    lore: 'Năm lần vượt ải — ý chí ngươi đã được thử thách đủ rồi.',
  },
  {
    id: 'side_dungeon_01',
    name: 'Địa Phủ Sơ Thám',
    type: 'side', category: 'dungeon',
    desc: 'Hoàn thành 5 tầng dungeon.',
    unlockRealm: 1,
    objectives: [{ key: 'dungeon_floor', label: 'Tầng dungeon', required: 5 }],
    rewards: { stone: 90, exp: 900 },
    repeatable: false,
    lore: 'Địa Phủ không phải nơi để thăm quan — nhưng phần thưởng thì xứng đáng.',
  },

  // ============================================================
  // SECT INTRO QUESTS — quest đầu tiên cho người gia nhập tông môn ngay
  // ============================================================
  {
    id: 'sq_sect_intro_kiem_tong',
    name: 'Nhập Môn Thanh Vân',
    type: 'story', chain: 'sect', order: 0,
    desc: 'Gặp Trưởng Lão Kiếm để nhận nhiệm vụ đầu tiên của môn phái.',
    unlockRealm: 0,
    objectives: [{ key: 'talk_npc', target: 'elder', label: 'Gặp Trưởng Lão Kiếm', required: 1 }],
    rewards: { stone: 10, exp: 80, unlockQuest: 'sq_01_first_kill' },
    lore: '"Ngươi đến rồi. Ta đã nghe tin về linh căn của ngươi. Thanh Vân Kiếm Tông chào đón ngươi."',
    npcHint: '🏯 Vào cổng tông môn → tìm Trưởng Lão Kiếm Lão để nhận nhiệm vụ đầu tiên.',
  },
  {
    id: 'sq_sect_intro_dan_tong',
    name: 'Nhập Môn Vạn Linh',
    type: 'story', chain: 'sect', order: 0,
    desc: 'Gặp Vạn Linh Đan Lão để nhận chỉ dẫn đầu tiên về đan đạo.',
    unlockRealm: 0,
    objectives: [{ key: 'talk_npc', target: 'elder', label: 'Gặp Đan Lão', required: 1 }],
    rewards: { stone: 10, exp: 80, unlockQuest: 'sq_01_first_kill' },
    lore: '"Lửa đan sẽ phán xét ngươi. Trước tiên, hãy để ta xem tay ngươi có mang mùi thảo dược không."',
    npcHint: '⚗ Vào cổng Vạn Linh Đan Tông → tìm Vạn Linh Đan Lão để bắt đầu.',
  },
  {
    id: 'sq_sect_intro_tran_phap',
    name: 'Nhập Môn Huyền Cơ',
    type: 'story', chain: 'sect', order: 0,
    desc: 'Tìm Huyền Cơ Trận Lão tại Huyền Cơ Các để được chỉ dạy những điều cơ bản về trận pháp.',
    unlockRealm: 0,
    objectives: [{ key: 'talk_npc', target: 'elder', label: 'Gặp Trận Lão', required: 1 }],
    rewards: { stone: 10, exp: 80, unlockQuest: 'sq_01_first_kill' },
    lore: '"Trận pháp không có bắt đầu và kết thúc. Chỉ có quy tắc. Ngươi đã sẵn sàng học chưa?"',
    npcHint: '🔮 Vào cổng Huyền Cơ Các → tìm Huyền Cơ Trận Lão để nhận nhiệm vụ đầu tiên.',
  },
  {
    id: 'sq_sect_intro_the_tu',
    name: 'Nhập Môn Thiết Cốt',
    type: 'story', chain: 'sect', order: 0,
    desc: 'Ra mắt Thiết Cốt Môn Lão — trưởng lão đầy quyền uy của Thiết Cốt Môn.',
    unlockRealm: 0,
    objectives: [{ key: 'talk_npc', target: 'elder', label: 'Gặp Môn Lão', required: 1 }],
    rewards: { stone: 10, exp: 80, unlockQuest: 'sq_01_first_kill' },
    lore: '"Thân thể yếu ớt thì linh lực cao cũng vô dụng. Thiết Cốt Môn không cần thiên tài — cần người dám chịu đau."',
    npcHint: '💪 Vào cổng Thiết Cốt Môn → tìm Thiết Cốt Môn Lão để bắt đầu hành trình.',
  },

  // ============================================================
  // DAILY QUESTS — reset mỗi ngày game (không phải thực)
  // ============================================================
  {
    id: 'daily_kill_3',
    name: '[Nhật Tu] Liệp Yêu',
    type: 'daily',
    desc: 'Diệt 3 yêu thú hôm nay.',
    unlockRealm: 0,
    objectives: [{ key: 'kill', label: 'Diệt yêu thú', required: 3 }],
    rewards: { stone: 20, exp: 120 },
  },
  {
    id: 'daily_kill_10',
    name: '[Nhật Tu] Thập Yêu Trảm',
    type: 'daily',
    desc: 'Diệt 10 yêu thú hôm nay.',
    unlockRealm: 1,
    objectives: [{ key: 'kill', label: 'Diệt yêu thú', required: 10 }],
    rewards: { stone: 40, exp: 300 },
  },
  {
    id: 'daily_alchemy_1',
    name: '[Nhật Tu] Luyện Đan',
    type: 'daily',
    desc: 'Luyện đan 1 lần thành công hôm nay.',
    unlockRealm: 1,
    objectives: [{ key: 'alchemy', label: 'Luyện đan', required: 1 }],
    rewards: { stone: 15, exp: 100 },
  },
  {
    id: 'daily_alchemy_3',
    name: '[Nhật Tu] Tam Đan Thành',
    type: 'daily',
    desc: 'Luyện đan thành công 3 lần hôm nay.',
    unlockRealm: 2,
    objectives: [{ key: 'alchemy', label: 'Luyện đan', required: 3 }],
    rewards: { stone: 36, exp: 280 },
  },
  {
    id: 'daily_gather_5',
    name: '[Nhật Tu] Thu Thảo',
    type: 'daily',
    desc: 'Thu thập nguyên liệu 5 lần hôm nay.',
    unlockRealm: 1,
    objectives: [{ key: 'gather', label: 'Thu thập', required: 5 }],
    rewards: { stone: 18, exp: 110 },
  },
  {
    id: 'daily_gather_10',
    name: '[Nhật Tu] Đại Thu Hoạch',
    type: 'daily',
    desc: 'Thu thập nguyên liệu 10 lần hôm nay.',
    unlockRealm: 2,
    objectives: [{ key: 'gather', label: 'Thu thập', required: 10 }],
    rewards: { stone: 30, exp: 220 },
  },
  {
    id: 'daily_meditate_10m',
    name: '[Nhật Tu] Bế Quan',
    type: 'daily',
    desc: 'Bế quan tu luyện tổng cộng 10 phút.',
    unlockRealm: 0,
    objectives: [{ key: 'meditate_time', label: 'Thời gian bế quan (giây)', required: 600 }],
    rewards: { stone: 25, exp: 150 },
  },
  {
    id: 'daily_meditate_30m',
    name: '[Nhật Tu] Thâm Nhập Thiền Định',
    type: 'daily',
    desc: 'Bế quan tu luyện tổng cộng 30 phút.',
    unlockRealm: 1,
    objectives: [{ key: 'meditate_time', label: 'Thời gian bế quan (giây)', required: 1800 }],
    rewards: { stone: 50, exp: 380 },
  },
  {
    id: 'daily_dungeon_1',
    name: '[Nhật Tu] Địa Phủ Tuần Tra',
    type: 'daily',
    desc: 'Hoàn thành 1 tầng dungeon hôm nay.',
    unlockRealm: 1,
    objectives: [{ key: 'dungeon_floor', label: 'Tầng dungeon', required: 1 }],
    rewards: { stone: 24, exp: 180 },
  },
  {
    id: 'daily_explore_3',
    name: '[Nhật Tu] Du Lịch Hành Cước',
    type: 'daily',
    desc: 'Khám phá/hành động 3 lần trong thế giới.',
    unlockRealm: 0,
    objectives: [{ key: 'explore', label: 'Khám phá', required: 3 }],
    rewards: { stone: 15, exp: 90 },
  },
  {
    id: 'daily_breakthrough',
    name: '[Nhật Tu] Đột Phá Tinh Tấn',
    type: 'daily',
    desc: 'Đột phá cảnh giới 1 lần hôm nay.',
    unlockRealm: 0,
    objectives: [{ key: 'breakthrough', label: 'Đột phá', required: 1 }],
    rewards: { stone: 60, exp: 500 },
  },

  // ============================================================
  // BOUNTY QUESTS — tiêu diệt mục tiêu cụ thể, phần thưởng cao
  // Reset theo tuần hoặc khi hoàn thành (repeatable với cooldown)
  // ============================================================
  {
    id: 'bounty_wolf_pack',
    name: '[Truy Sát] Bầy Sói Đêm',
    type: 'bounty',
    desc: 'Tiêu diệt 5 Yêu Sói Đen — truy nã cấp địa phương.',
    unlockRealm: 0,
    objectives: [{ key: 'kill_specific', target: 'demon_wolf', label: 'Diệt Yêu Sói Đen', required: 5 }],
    rewards: { stone: 50, exp: 350 },
    repeatable: true,
    cooldownHours: 24,
    lore: 'Thông báo truy nã: Bầy sói yêu 7 con quấy phá vùng ngoại ô. Ai diệt được thưởng nặng.',
  },
  {
    id: 'bounty_stone_golem',
    name: '[Truy Sát] Thổ Nguyên Cự Thạch',
    type: 'bounty',
    desc: 'Tiêu diệt 3 Thổ Nguyên Quỷ đang cản trở khai thác linh mạch.',
    unlockRealm: 0,
    objectives: [{ key: 'kill_specific', target: 'stone_golem', label: 'Diệt Thổ Nguyên Quỷ', required: 3 }],
    rewards: { stone: 60, exp: 400 },
    repeatable: true,
    cooldownHours: 24,
    lore: 'Linh mạch phía đông bị Thổ Nguyên Quỷ chiếm. Hội Thương Nhân trả tiền để dọn sạch.',
  },
  {
    id: 'bounty_fire_fox',
    name: '[Truy Sát] Hỏa Hồ Tác Quái',
    type: 'bounty',
    desc: 'Tiêu diệt 5 Hỏa Linh Hồ đốt cháy nhà dân.',
    unlockRealm: 0,
    objectives: [{ key: 'kill_specific', target: 'fire_fox', label: 'Diệt Hỏa Linh Hồ', required: 5 }],
    rewards: { stone: 70, exp: 450 },
    repeatable: true,
    cooldownHours: 24,
    lore: 'Đêm qua ba ngôi nhà bị thiêu rụi. Hồ linh phóng hỏa từ trong bóng tối.',
  },
  {
    id: 'bounty_thunder_hawk',
    name: '[Truy Sát] Lôi Ưng Không Phận',
    type: 'bounty',
    desc: 'Tiêu diệt 3 Lôi Ưng Quỷ đang kiểm soát bầu trời vùng này.',
    unlockRealm: 1,
    objectives: [{ key: 'kill_specific', target: 'thunder_hawk', label: 'Diệt Lôi Ưng Quỷ', required: 3 }],
    rewards: { stone: 90, exp: 900 },
    repeatable: true,
    cooldownHours: 48,
    lore: 'Đường hàng không bị phong tỏa. Không phi kiếm nào dám bay qua vùng đó.',
  },
  {
    id: 'bounty_ice_serpent',
    name: '[Truy Sát] Băng Xà Phong Lộ',
    type: 'bounty',
    desc: 'Tiêu diệt 2 Băng Hàn Xà phong tỏa tuyến đường linh dược.',
    unlockRealm: 1,
    objectives: [{ key: 'kill_specific', target: 'ice_serpent', label: 'Diệt Băng Hàn Xà', required: 2 }],
    rewards: { stone: 105, exp: 1000 },
    repeatable: true,
    cooldownHours: 48,
    lore: 'Tuyến đường vận chuyển linh dược từ băng sơn bị hai con Băng Hàn Xà chiếm đóng.',
  },
  {
    id: 'bounty_demon_general',
    name: '[Truy Sát] Thảo Phạt Yêu Tướng',
    type: 'bounty',
    desc: 'Tiêu diệt Yêu Tướng Hắc Giáp — kẻ thù số một vùng linh địa.',
    unlockRealm: 2,
    objectives: [{ key: 'kill_specific', target: 'demon_general', label: 'Diệt Yêu Tướng Hắc Giáp', required: 1 }],
    rewards: { stone: 300, exp: 3000 },
    repeatable: true,
    cooldownHours: 72,
    lore: 'Yêu Tướng Hắc Giáp tái xuất. Mỗi lần nó xuất hiện là một lần thảm họa.',
  },
  {
    id: 'bounty_jade_serpent',
    name: '[Truy Sát] Bích Ngọc Xà Linh',
    type: 'bounty',
    desc: 'Tiêu diệt 1 Bích Ngọc Thần Xà — linh vật nguy hiểm bậc nhất.',
    unlockRealm: 3,
    objectives: [{ key: 'kill_specific', target: 'jade_serpent', label: 'Diệt Bích Ngọc Thần Xà', required: 1 }],
    rewards: { stone: 400, exp: 6000 },
    repeatable: true,
    cooldownHours: 72,
    lore: 'Bích Ngọc Thần Xà xuất hiện mỗi trăm năm một lần. Ai diệt được sẽ trở thành huyền thoại.',
  },
  {
    id: 'bounty_phantom_fox_elite',
    name: '[Truy Sát] Ảo Ảnh Ma Hồ',
    type: 'bounty',
    desc: 'Tiêu diệt 2 Ảo Ảnh Cửu Vĩ Hồ đang thu thập linh lực người tu.',
    unlockRealm: 3,
    objectives: [{ key: 'kill_specific', target: 'phantom_fox', label: 'Diệt Ảo Ảnh Cửu Vĩ Hồ', required: 2 }],
    rewards: { stone: 500, exp: 7000 },
    repeatable: true,
    cooldownHours: 72,
    lore: 'Hai con Cửu Vĩ Hồ hóa thành thiếu nữ để dụ dỗ và hút cạn linh lực tu sĩ.',
  },

  // ============================================================
  // SECT QUESTS — chỉ cho thành viên tông môn
  // ============================================================
  {
    id: 'sect_patrol_01',
    name: '[Tông Vụ] Tuần Tra Lãnh Thổ',
    type: 'sect',
    desc: 'Tuần tra lãnh thổ tông môn, diệt yêu thú xâm nhập.',
    unlockRealm: 0,
    requireSect: true,
    objectives: [{ key: 'kill', label: 'Diệt yêu thú xâm nhập', required: 5 }],
    rewards: { stone: 30, exp: 200, sectExp: 100 },
    repeatable: true,
    cooldownHours: 12,
    lore: 'Bảo vệ lãnh thổ là bổn phận của mỗi đệ tử.',
  },
  {
    id: 'sect_herb_collect',
    name: '[Tông Vụ] Thu Thảo Cung Cấp',
    type: 'sect',
    desc: 'Thu thập linh thảo cho kho dược của tông môn.',
    unlockRealm: 0,
    requireSect: true,
    objectives: [{ key: 'gather', label: 'Thu thập nguyên liệu', required: 8 }],
    rewards: { stone: 24, exp: 160, sectExp: 80 },
    repeatable: true,
    cooldownHours: 12,
    lore: 'Kho dược của tông môn luôn cần được bổ sung. Đây là việc không bao giờ hết.',
  },
  {
    id: 'sect_alchemy_supply',
    name: '[Tông Vụ] Cung Cấp Đan Dược',
    type: 'sect',
    desc: 'Luyện đan 3 lần để cung cấp cho tông môn.',
    unlockRealm: 1,
    requireSect: true,
    objectives: [{ key: 'alchemy', label: 'Luyện đan cho tông', required: 3 }],
    rewards: { stone: 60, exp: 400, sectExp: 200 },
    repeatable: true,
    cooldownHours: 24,
    lore: 'Đan dược luôn là tài nguyên quý. Tông môn không bao giờ từ chối đệ tử luyện đan.',
  },
  {
    id: 'sect_escort_mission',
    name: '[Tông Vụ] Hộ Tống Thương Đội',
    type: 'sect',
    desc: 'Hộ tống thương đội tông môn qua vùng nguy hiểm — tiêu diệt 10 yêu thú.',
    unlockRealm: 1,
    requireSect: true,
    objectives: [{ key: 'kill', label: 'Bảo vệ thương đội', required: 10 }],
    rewards: { stone: 80, exp: 600, sectExp: 300 },
    repeatable: true,
    cooldownHours: 24,
    lore: 'Thương đội mang hàng hóa quan trọng. Mất hàng là mất mặt tông môn.',
  },
  {
    id: 'sect_elite_hunt',
    name: '[Tông Vụ] Tiêu Diệt Yêu Thú Tinh Nhuệ',
    type: 'sect',
    desc: 'Tiêu diệt yêu thú mạnh đang đe dọa vùng linh địa tông môn.',
    unlockRealm: 2,
    requireSect: true,
    objectives: [{ key: 'kill_tier', minTier: 4, label: 'Diệt yêu thú mạnh', required: 3 }],
    rewards: { stone: 120, exp: 1200, sectExp: 500 },
    repeatable: true,
    cooldownHours: 48,
    lore: 'Chỉ có đệ tử xuất sắc mới được giao nhiệm vụ loại này.',
  },
];

// ---- Export helpers ----
export const DAILY_QUEST_IDS = QUESTS
  .filter(q => q.type === 'daily')
  .map(q => q.id);

export const STORY_QUEST_IDS = QUESTS
  .filter(q => q.type === 'story')
  .map(q => q.id);

export const BOUNTY_QUEST_IDS = QUESTS
  .filter(q => q.type === 'bounty')
  .map(q => q.id);

export const SECT_QUEST_IDS = QUESTS
  .filter(q => q.type === 'sect')
  .map(q => q.id);